### ISSUE TITLE
splicing bubbles

### ISSUE THREAD

**Issue by kya-hover** [Montana-Media-Arts/120_CreativeCoding#100]
I attempted to write a code where my bubble objects would "pop" when they collided with one another. The problem that kept coming up was when I had more than just two bubble objects...as soon as one pair touched they were all spliced! I wanted to try to get only the two bubbles that touch to delete each other. Is there anything I am doing wrong or should add to fix this? 
```destroy(otherBubbles, my_id) {
      for (let n = 0; n < otherBubbles.length; n++) {
        if (n != my_id) {
            let d = dist(this.x, this.y, otherBubbles[n].x, otherBubbles[n].y);
            let combinedR = this.radius + otherBubbles[n].radius;
            for (let i = bubbles.length -1; i >= 0; i--) {
            if (d <= combinedR) {
              bubbles.splice(i, 1)```

**Comment by ReadReedRed** [comment]
@kya-hover I'm afraid I'm not sure what might've caused this either, but it might help to look at the collision code from one of the examples in this week's module (the Happy Faces example that deletes upon collision and regenerates a new face elsewhere to keep the sketch active). I've copied and pasted the chunk that might help you most below for comparison! 

`checkCollisions(objArr, myIdx) {
        for (var i = 0; i < objArr.length; i++) {
            if (myIdx !== i) {
                var obj = objArr[i];
                var objDist = dist(this.loc.x, this.loc.y, obj.loc.x, obj.loc.y);
                var maxDist = this.rad + obj.rad;
                if (objDist <= maxDist) {
                    this.delta.x *= -1;
                    this.delta.y *= -1;
                    if (canCreateNewHappyFace) {
                        createNewHappyFace();
                        canCreateNewHappyFace = false;
                    }
                    killHappyFace(myIdx);
                }
            }
        }
    }`

**Comment by kya-hover** [comment]
@MarkLannenUM 
I was using 'i' other places in my sketch, and I tried changing it like you suggested. It still isn't working like I want, but it was a good thought!

**Comment by kya-hover** [comment]
@ReadReedRed 
Thanks! I forgot that that example sketch used deletions. My code is working a little better now. :)

**Comment by MarkLannenUM** [comment]
@kya-hover 
Sorry that did not work! It was causing me a problem once, but must have been a different issue.
