### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by YewTreeDesign** [Montana-Media-Arts/120_CreativeCoding#101]
I am having troubles.
So I am coding in collision detection

https://yewtreedesign.github.io/120-work/hw-12/

but I want to include images.

I want the images to change when they collide.

Here's what I have so far;

`

let seal;
let boop;

function preload(){

seal = new Bubble loadImage('seals/seal.png');

boop = new Bubble loadImage('seals/boop.png');

}

function setup() {
  createCanvas(600, 400);

}

function draw() {
  background(0);

  if (seal.intersects(boop)) {
    background(200, 247, 247);
  }

  seal.show();
  boop.show();
  seal.move();
  boop.x = mouseX;
  boop.y = mouseY;

}

class Bubble {
  constructor(x, y, r, img) {
    this.x = x;
    this.y = y;
    this.r = r;
    this.seal= img;
  }

  intersects(other) {
    let d = dist(this.x, this.y, other.x, other.y);
    return (d < this.r + other.r);

    if (d < this.r + other.r) {
      this.seal = boop;
    //   return true;
    // } else {
    //   return false;
     }

  }

  contains(px, py) {
    let d = dist(px, py, this.x, this.y);
    if (d < this.r) {
      return true;
    } else {
      return false;
    }
  }

  move() {
    this.x = this.x + random(-2, 2);
    this.y = this.y + random(-2, 2);
  }

  show() {
    image(this.seal, this.x, this.y, this.r);
  }
}

`
here's the images:

![boop](https://user-images.githubusercontent.com/35701097/39028829-fff869c8-4415-11e8-9fe9-e570e89df457.png)
![seal](https://user-images.githubusercontent.com/35701097/39028830-00101a64-4416-11e8-9402-5dfa939fb950.png)

I am stuck and it shows up blank in the browser. What am I doing wrong?

**Comment by quintinbruderer** [comment]
I did not test this yet, however I see in your intercect function you RETURN (d <this.r + other.r). Whenever you return something in a function, it completes the function and wont continue. So it isn't getting to your if statement. 

I would rewrite like...
```
intersects(other) {
  let d = dist(this.x, this.y, other.x, other.y);
  let intersect = (d < this.r + other.r);

  if (intersect) {
    this.seal = boop;
    return true;
   } else {
   return false; 
  *and reset it to regular seal*
  }
}
```
