### ISSUE TITLE
Blinking alternating light

### ISSUE THREAD

**Issue by dafredichini22** [Montana-Media-Arts/120_CreativeCoding#102]
For my assignment, my idea is to create a classic cinema billboard, where it has flashing lights and names of shows that are appearing. But I'm having trouble coding the ellipses within a for loop to continuously change back and forth from grey to yellow. 
I was thinking about using an if statement within the loop and that worked for alternating the grey and yellow ellipses but it doesn't continue to change back and forth.
So does anyone know how I can get the fill() of the ellipses to continuously alternate between the two colors? 
Here's what I have so far for one of the ellipse loops:
link to full sketch: https://github.com/dafredichini22/120-work/blob/master/hw-8/sketch.js

function draw() {
  var col1 = 255;
  let bulbWidth = 20;
  let bulbHeight = 30;
  let moveY = 150;

for (let i = 100; i < windowWidth - 100; i += 30) {

       fill(col1, col1, 0);
       if (col1 == 255){
          col1 = 50;
        }
       else {
         col1 = 255;
       }
    ellipse(i, moveY, bulbWidth, bulbHeight);
      }

**Comment by MarkLannenUM** [comment]
Hi @dafredichini22 

I'm wondering if the issue is that I don't see in your code where you change the value of col1 (increment or decrement). Therefore it seems that the variable col1 will always evaluate as 255 and the 'else' part of the 'if else' statement will never happen as col1 will always equal 255. 

Let me know if I'm on the right track!

**Comment by dafredichini22** [comment]
@MarkLannenUM 
I tried doing: 
  var col1 = 255;
  var col2 = 255;
  var col3 = 0;
  var col4 = 50;

if (col1 == col2){
  col1 = 50;
  col2 -= 1;
}
else {
  col1 = 255;
  col2 += 1;
}

but that didn't do anything different. When I place the if statement outside the for loop, it turns all the ellipses grey. 

I'm trying to see if I could add another variable and do something like this:
var change = true;

if (change = true){
  if (col1 == 255){
    col1 = 50;
    change = false;
  }
  else {
    col1 = 255;
    change = false;
  }
}
else{
  if (col1 != 255){
    col1 = 255;
    change = true;
  }
  else {
    col1 = 50;
    change = true;
  }
}

but that doesn't work either. Any other suggestions???

**Comment by MarkLannenUM** [comment]
Would you be able to post the entire code? I don't know if I'd be able to get anywhere with it, but if I had the whole thing I could tinker with it and see if I could get it to work.

Might be a question for one of the lab assistants!  :)

**Comment by dafredichini22** [comment]
@MarkLannenUM 
I'll post the entire code below. It's messy and a bit confusing so if you have any questions or suggestions, let me know. 
Also, I tried using a while loop to get the blinking lights to work but I still was unsuccessful. I did however managed to get all the lights to alternate colors once, but then it stopped. 


Code link: https://github.com/dafredichini22/120-work/blob/master/hw-8/sketch.js
Code:

var change = true;
let option = 1;
let timer = 1;

function setup() {
    createCanvas(windowWidth, 700);
    background(0);

    frameRate(2);
  }

function draw() {
  var col1 = 255;
  var col2 = 255;
  var col3 = 0;
  var col4 = 50;

  let bulbWidth = 20;
  let bulbHeight = 30;

  //Background to billbaord
  fill('rgb(240, 242, 218)');
  stroke(5);
  rect(90, 180, windowWidth - 220, 300);

  //Lines on billboard
  for (let k = 225; k < 500; k += 50){
    line(100, k, windowWidth - 120, k);

  }

  //Top and bottom grey bars
  for (let h = 165; h < 700; h += 304){
    noStroke();
    fill (50, 50, 50);
    rect (90, h, windowWidth - 205, 15);

    //Not needed anymore. Saved just incase.
    //rect (90, 165, windowWidth - 205, 15);
    //rect (90, 469, windowWidth - 205, 15);

  }

  //Side grey bars
  for (let f = 90; f < windowWidth - 50; f += windowWidth - 220){
    noStroke();
    fill (50, 50, 50);
    rect (f, 166, 15, 304);

  }

  //Make lights alternate colors

timer++;


while (timer < 4){
  timer++;
  if(timer % 2 == 0){
    col1 = 50;
  }
  else {
    col1 = 255;
  }
}

/*
  if (timer % 2 == 0) {
    while (timer < 100){
        col1 = 50;
      /*
      if (col1 == col2){
        col1 = 50;
      }
      */
      /*
      timer++;
    }
  }
  else {
    while (timer < 1000){
      col1 = 255;
      /*
      if (col1 == col4){
        col1 = 255;
      }
      */
      /*
    timer++;
    }
  }
/*
  else if (col1 == col4) {
    col1 = 255;
    //col2 += 1;
  }
  else {
    col3 = 0;
  }
*/



  //Top and bottom string of lights
  for (let moveY  = 150; moveY < 700; moveY += 350) {
    for (let i = 100; i < windowWidth - 100; i += 30) {
      /*
      if (change) {
          }
        change = false;
      }
      else {
        change = true;
      }
      */

      fill(col1, col1, 0);


      if (col1 == 255){
        col1 = 50;
      }
      else {
        col1 = 255;
      }

/*
if (change = true){
  if (col1 == 255){
    col1 = 50;
    change = false;
  }
  else {
    col1 = 255;
    change = false;
  }
}
else{
  if (col1 != 255){
    col1 = 255;
    change = true;
  }
  else {
    col1 = 50;
    change = true;
  }
}
*/

      ellipse(i, moveY, bulbWidth, bulbHeight);

        }
      }

    //Left and right string of lights
    for (let moveX = 74; moveX < windowWidth - 50; moveX += windowWidth - 173) {
      for (let j = 175; j < 500; j += 30) {

        fill(col1, col1, 0);
        if (col1 == 255){
          col1 = 50;
        }
        else {
          col1 = 255;
        }
        ellipse(moveX, j, bulbHeight, bulbWidth);
      }
    }






if (option == 1) {
  textSize(40);
  fill(0);
  text('Avengers: Infinity War', windowWidth/2 - 200, 275);
  text('2:30, 4:30, 6:30, 8:30, 10:30', windowWidth/2 - 265, 325);

}
else if (option == 2) {
  textSize(40);
  fill(0);
  text('A Quiet Place', windowWidth/2 - 135, 275);
  text('3:45, 5:30, 7:15, 9:00, 10:45', windowWidth/2 - 265, 325);

}
else {
  textSize(40);
  fill(0);
  text('A Wrinkle in Time', windowWidth/2 - 160, 275);
  text('3:00, 6:00, 9:00, 12:00', windowWidth/2 - 215, 325);

}
}


function mousePressed() {
  option++;
  if (option > 3) option = 1;
}

**Comment by dafredichini22** [comment]
@MarkLannenUM 
Don't worry. It's fixed now. I just had to take out the while loop I had for the alternating colors part.

**Comment by MarkLannenUM** [comment]
@dafredichini22 
Glad you got it to work!
