### ISSUE TITLE
Classes and this.

### ISSUE THREAD

**Issue by dafredichini22** [Montana-Media-Arts/120_CreativeCoding#103]
Is it alright to have classes with the same this.'s??? 
For example could I have
class Ball {

constructor(){
this.loc_x = random(100);
}
}

class Stick {

constructor(){
this.loc_x = random(100);
}
}

Like is this ok or do I need to change the this. within the constructor?

**Comment by MarkLannenUM** [comment]
@dafredichini22 

I experimented changing the this.'s in my classes so they were the same across several classes, and it did not break my sketch. So, as far as I can they act as local variables, and what you have above should be fine. Let me know if you find out otherwise!
