### ISSUE TITLE
Is anyone else working with sound and having this issue?

### ISSUE THREAD

**Issue by iballs** [Montana-Media-Arts/120_CreativeCoding#104]
<img width="1440" alt="screen shot 2018-05-02 at 3 34 13 pm" src="https://user-images.githubusercontent.com/26286851/39550443-81940c8c-4e1e-11e8-9294-3d4bb4ed22e2.png">

**Comment by iballs** [comment]
No matter what I do it keeps saying that loadSound is undefined?

**Comment by michaelmusick** [comment]
Did you uncomment the p5.sound.min.js line within your HTML document?

--
Michael Musick

michaelmusick.com<http://michaelmusick.com>

On May 2, 2018, at 3:36 PM, Ian Baldessari <notifications@github.com<mailto:notifications@github.com>> wrote:


No matter what I do it keeps saying that loadSound is undefined?

**Comment by iballs** [comment]
I would've never have caught this, thank you.

**Comment by MarkLannenUM** [comment]
I'm having an issue with a sound file. I've taken a screenshot of the code below where I declare the variable 'song,' define it in the preLoad function, and then in setup call it - song.play();

However, the song does not play, and when I inspect the element in Firefox, I get - **TypeError: song is undefined**  which I don't understand as I think I have done that in the code.

Any suggestions welcome!

And yes, I have uncommented the p5 sound line in the html.  :)  

![screen shot 2018-05-06 at 8 08 25 pm](https://user-images.githubusercontent.com/31551434/39681768-6088a00e-5169-11e8-9532-10dd86c43b06.png)

**Comment by michaelmusick** [comment]
As with the setup and draw functions. You can only define preLoad a single time. I imagine that when you define a second time, the song variable is getting collected by garbage. Therefore, combine your two preLoad functions into a single preLoad functions definition. I think that will fix it?

**Comment by egriffin2** [comment]
I'm pretty sure that's exactly what it was, I just looked at this in another thread in the forum and it sounds like it's working now.

**Comment by MarkLannenUM** [comment]
Yep - it is fixed now. Thanks to both of you!
