### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Amann22** [Montana-Media-Arts/120_CreativeCoding#105]
Hey all, I am currently attempting to put in image into my project, I have even copied the given example exactly(with my own photo) and every time I just receive a loading icon that never disappears. I am attempting to insert a small image that will depict the player in my game.

**Comment by MarkLannenUM** [comment]
I was having the same issue. The fix turned out to be that I needed to set up a local server on atom.  Instructions from week 13 material: https://montana-media-arts.github.io/creative-coding-1/modules/week-13/local-server/

When I did that my image loaded correctly.   

Let me know if that helps!

**Comment by Amann22** [comment]
I could open the server before and this made it able for me to open a sketch via clicking on the specific folder in the server. However, this lasted only ten minutes and I am still unable to see the photo. The server pulled up on my browser now shows my photo while I am still unable to access it via atom. Working on it now, getting farther, thanks Mark!!

**Comment by MarkLannenUM** [comment]
@Amann22 
_"-is there a way to work on a sketch with an image without having to"_ 
If I'm understanding your question - could you comment out the preload function until you get the server issue sorted? I think that is what I did until I worked out what was going wrong.

Also, what browser are you using? I found that Chrome was problematic and would stop for no reason that I could understand. In my experience **Firefox** has worked the best for me when using a local server.

Hope that helps!

**Comment by mabonmoon** [comment]
If you're using chrome as your browser, it is likely that. I about lost my mind with this same issue. I installed the local server in atom, and downloaded firefox and images work now! Yaaaay.
