### ISSUE TITLE
Sketch won't load correctly when I upload it to Github?

### ISSUE THREAD

**Issue by iballs** [Montana-Media-Arts/120_CreativeCoding#107]
[Live Sketch](https://iballs.github.io/120-work/final_project/demos/sound_demo%20copy%202/)

[Code](https://github.com/iballs/120-work/tree/master/final_project/demos/sound_demo%20copy%202)

My code seems to work fine when I run it on a server, but when I push it to GitHub the mp3 file will not play?

**Comment by iballs** [comment]
*Also it's not finished, just wanted to test it out, the play button is at the bottom left.

**Comment by egriffin2** [comment]
Did you push the mp3 file to github as well?  If you haven't put the mp3 file onto github then the sketch won't be able to access it.  Right now your sketch is accessing the mp3 file locally on your computer but if the mp3 isn't on github then there will be no file for the sketch to use.

**Comment by iballs** [comment]
I did, turns out it works in safari, it must be a problem with the chrome web browser
