### ISSUE TITLE
Atom on Windows

### ISSUE THREAD

**Issue by zeemakn** [Montana-Media-Arts/120_CreativeCoding#117]
I am runnin Windows and can't figure out how to make all text files open in atom. Also I can't figure out how to install shell commands in atom. Can anybody help?

**Comment by spkvfx** [comment]
I do not have windows in front of me, but this should help as far as default files:

https://support.microsoft.com/en-us/help/4028161/windows-10-change-default-programs

I do not use Atom, so I am not sure about how to install the terminal support. Maybe these will help?

https://flight-manual.atom.io/using-atom/sections/atom-packages/
https://atom.io/packages/atom-terminal

**Comment by Schrielle360** [comment]
@zeemakn to open a text file in atom make sure its first in the proper folder that you wanted it in, also that its a .txt file. Then you go to open folder and open the folder its in. That will automatically open the file. Or you can create a new file if that helps any? I am not sure. 
Also @spkvfx also has some good links if what you're looking for is more that.

**Comment by spkvfx** [comment]
As far as getting the atom terminal, it would seem that you could use win-R to open a new terminal, and then type:

`apm install atom-terminal`

If I understand it, this should execute the Atom Package Manager and install the atom-terminal package. I would imagine you'll need an interweb connection and it'll just download everything you need to make the package work (similar to apt/yum on Linux)

If that works, then restart Atom and cntrl-shift-t to open a new terminal starting at the current project directory. If it downloaded and installed but did not work, you might need to activate the package, see my first link from the atom manual.

**Comment by Codykrull** [comment]
I had the same problem as I'm also using Windows, but I decided to just open the program with the executable and move on with the assignment. I tried finding a solution, but it all just seems a little too complicated for me at the moment as it seems you need make windows on a command level understand the shortcut to launch the program. Much like you have to establish the powershell with a Mac computer. Let me know if you find a solution!

**Comment by spkvfx** [comment]
On a mac it isn't too difficult. You just Get Info then "Open With" then there is some checkbox that is something like 'Always Open With This'. If the windows support file I linked does not work, power users can directly associate file types using the registry, but I would not recommend this approach unless you're already familiar with how to do so; but if you _really_ want to break your PC:

https://docs.microsoft.com/en-us/windows/desktop/shell/default-programs

Keep in mind that the way the operating system knows what file type it is will be by the extension. So if you define a .txt to always open with Atom, this will not extend to .js or .md

**Comment by scottyG86** [comment]
On Windows, you should be able to set the default program to open text files by right-clicking your file that you want to open, open with, select Atom and there should be a box to open all files of this type with this program. Hope this helps!!

**Comment by HagenNathaniel** [comment]
Adding to @scottyG86 comment, you might be interested in changing what windows uses as a default program to open the specific files..

On Windows 10..
https://support.microsoft.com/en-us/help/4028161/windows-10-change-default-programs

Windows 7:
https://support.microsoft.com/en-us/help/18539/windows-7-change-default-programs

This way, you can just double click the file, and windows will do the rest (most of the time).

**Comment by RyanMiskiv** [comment]
You can right click on the type of file you want to change, click properties, and then, click `Change...` next to **Opens with:** and change the program to Atom.
