### ISSUE TITLE
Issues with embedding screenshot?

### ISSUE THREAD

**Issue by erinflint** [Montana-Media-Arts/120_CreativeCoding#119]
I'm using atom on mac and for some reason my screenshot will not show up correctly on my final github page. My brackets aren't appearing as green, they're white instead. I've renamed it, attempted to retake it, etc. and am getting nowhere. It shows up as a link to a "404" error site. Help?

**Comment by mafordah** [comment]
I'm not super familiar with macs, but I know the title of the image has to be exact with all the spelling, capitalization etc. with no spaces. Could you post your code or a photo of what it looks like in your editor?

**Comment by mafordah** [comment]
There is also some information under Images in the [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images) that may be helpful.

**Comment by Schrielle360** [comment]
@erinflint Have you checked the spacing as well? that also has to be exact. Mine was white not green till i fixed the spacing between the brackets.

**Comment by lilyj521** [comment]
Mine is doing that too. Everything is definitely spelled right too, I have no clue what the issue is.

**Comment by michaelmusick** [comment]
@erinflint your picture is not pushed to the repo currently. Make sure you add your image to your github repo.

**Comment by erinflint** [comment]
@lilyj521 my issue ended up being exactly what Dr. Musick said (in the above response) and all I had to do was take my image and drag and drop it into my github repository and everything worked.
