### ISSUE TITLE
Pushing Changes to GitHub Server

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#120]
I think I'm doing something fundamentally wrong, I thought I had published my repository, committed all changes, and pushed it to the server... but there is nothing showing up that looks remotely like the homework assignment.  The assignment went fine, had no trouble with formatting or embedding the screenshot.  I just can't figure out how to get it where it needs to go.  I feel like maybe my brain is fried and I'm missing something super basic right now.  If anyone can help me out I would be incredibly appreciative.

**Comment by DVSnell** [comment]
Two screenshots are both visible and both show a blue dot on your `readme.md` tab meaning the file hasn't been saved with its current changes.  Make sure you save your completed `readme.md` in Atom and then try committing and pushing again.  You can use File->Save or Ctrl+s.  It looks like the file was pushed, but it's empty and only 10 bytes in size.

**Comment by JoleneTiffanyG** [comment]
I think it might have worked!  I still have no idea what's been happening the past hour.. but I just kept committing and pushing and I think it looks like it's supposed to now?  Or at least as close as I can apparently get it.  My gosh.   Thanks so much for your response.

**Comment by JoleneTiffanyG** [comment]
Oh except the screenshot is separate now.. it was there a minute ago

**Comment by DVSnell** [comment]
It looks good, but check the capital "S" on your screenshot link.  Remember that the assets you link to have to be exactly the same.  Even the file extension has to be the same.

**Comment by JoleneTiffanyG** [comment]
@DVSnell I just now saw your latest response, I wish I hadn't missed it before because the capitalized S was totally the problem and I took forever figuring it out.  Thank you!!
