### ISSUE TITLE
hw2

### ISSUE THREAD

**Issue by nathanruana** [Montana-Media-Arts/120_CreativeCoding#121]
hi i dont know if iam not doing it in the right spout but do we need to do the assingment in the get bash that we downlode last week or a diffrent one? Any help would be amazing I am stressing out bad.

**Comment by DVSnell** [comment]
You can use bash to make files and explore the directory, but most of the work will be done in Atom or any other text editor using the markdown language.

**Comment by brittdalton** [comment]
For week 2 homework: 

create a folder on your computer for HW-2. (you don't need to use bash for that you can do it the way you always have)

open Atom and create a new file and save it as readme.md in the HW-2 folder 

then use markup to style your text in that file

here is what my GitHub looks like when im done:


<img width="1058" alt="screen shot 2018-09-05 at 7 36 47 pm" src="https://user-images.githubusercontent.com/31601138/45129822-31216f00-b143-11e8-9ce5-a49fca818633.png">

then submit a link to Moodle for week 2 homework

Here is a link to mine if you need to see a finished one:
https://github.com/brittdalton/Creative_Coding_HW/blob/master/HW_02/Readme.md

If you click the "raw" you can see exactly how I formatted it, if you need more help with markup
<img width="1036" alt="screen shot 2018-09-05 at 7 45 01 pm" src="https://user-images.githubusercontent.com/31601138/45130117-87db7880-b144-11e8-8b27-019487fbdbfa.png">

**Comment by brittdalton** [comment]
It looks like you don't have a repository set up yet...you might just want to go back and go through the directions on the website and go through them one by one to get properly set up and all the applications installed before you attempt HW2...it will be worth it to get a good start in the applications that we are using and make sure your set up correctly

**Comment by nathanruana** [comment]
thanks
