### ISSUE TITLE
Appearance

### ISSUE THREAD

**Issue by hayliesunshine** [Montana-Media-Arts/120_CreativeCoding#123]
When I wrote my report in markdown in Atom, my pieces of code such as placing a link, making something bold, or showcasing code appeared to work, and turned colors. However, when I push it to my repository, they show up as markdown. Does anybody know why?
![markdown screenshot](https://user-images.githubusercontent.com/42792278/45200191-de23e680-b22c-11e8-8b42-8a3d93a9bac4.PNG)

**Comment by hayliesunshine** [comment]
This is my updated version, it is still not working.
![markdown screenshot 2](https://user-images.githubusercontent.com/42792278/45200539-88e8d480-b22e-11e8-9ffb-24ccc79b3c27.PNG)

![githubcom screenshot](https://user-images.githubusercontent.com/42792278/45200680-25ab7200-b22f-11e8-9aa4-a7f5f573b95b.JPG)

**Comment by brittdalton** [comment]
If you take the space out of the link - between the [] and the () it will work
```[Link] (website) ---> [Link](website) ```

**Comment by brittdalton** [comment]
I can see that your image is labeled Markdown screenshot.PNG but your link is labeled as ..markdown-screenshot-2.jpg they have to be exactly the same to show the image (im not sure how that space in the image name is going to translate) but if you have Markdown-screenshot.png you should have (/hw-2/Markdown-screenshot.png)

**Comment by hayliesunshine** [comment]
I made these changes, but it didn't do anything.

**Comment by DVSnell** [comment]
Each of your entries is indented 4 spaces, which markdown turns into a code block.  This removes your formatting and shows raw links.  Reduce the spacing before each hyphen and your formatting will work.  Remember that markdown also removes extra whitespace anyway, so such formatting is only useful for your personal work.

**Comment by hayliesunshine** [comment]
Thank you @DVSnell, that fixed my problem! However, my screenshot link still won't work. It shows up as a link, but does not actually link to anything. Do you know what could be wrong with it? The code I put is       ![Screenshot](..atom-screenshot.JPG), and I made sure the file name matches the name in the code.

**Comment by DVSnell** [comment]
So the screenshot file is `screenshot atom.JPG` but the link is `..screenshot atom.PNG`  You'll need to correct the file extension and set it to `./FILENAME GOES HERE`  The `./` tells it to look in the same directory as the `readme.md` file.

And if it doesn't stick, always Save, Commit, and Push again.

By the way, in Atom you can go to `Packages -> Markdown Preview -> Toggle Preview` or press `Ctrl+Shift+M` for a handy real time viewer like this:

![preview sample](https://user-images.githubusercontent.com/39629030/45245699-b4b19c00-b2ba-11e8-9e2a-2a2dc9a222ca.jpg)

**Comment by DVSnell** [comment]
Hey, @hayliesunshine remove the < and > as well as the hyphen from the screenshot line and you should be good to use it like a normal markdown link.  Sorry about that haha.
