### ISSUE TITLE
Starting Week 3 Project

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#124]
I'm just starting to try to set up for this week's project, and as far as I can see my folders are labeled and arranged correctly, the files are unzipped, etc. (see circled in first image) But in GitHub Desktop I'm not seeing anything inside the course-work folder other than an empty week-3 (which isn't even spelled correctly, which I don't understand since the source is spelled correctly and I wouldn't know how to change the folder name in GitHub even if I wanted to).  And then when I opened it in Atom (directly from GitHub Desktop) then week-3 is suddenly spelled correctly but still nothing inside.  I am So confused.   (also thank you so much to those of you who have been helping everyone else out, you are amazing)
![screenshot-folders](https://user-images.githubusercontent.com/42923897/45259672-29eea100-b38f-11e8-9a07-73fd8ab41308.jpg)
![screenshot-githubdesktop-atom](https://user-images.githubusercontent.com/42923897/45259677-370b9000-b38f-11e8-8f4a-2d40039bf015.png)

**Comment by DVSnell** [comment]
Couple of things to try here.  

* Mouse over the `Current Repository` button at the top of the GitHub App and make sure it matches the directory location you circled in screenshot one.  
* Another thing to do is `Right click` on the weird "wweek-3" in Atom and choose `Show in Explorer` to navigate directly to where that folder is located.  You can also do this with the correct "week-3" that is currently empty.  
* Then you can choose which one to make your actual repository by moving the necessary files there or choosing (in Atom) either `File -> Reopen Project` to find an old project directory or `File -> Add Project Folder` to make a new one.

Hope it helps.

**Comment by JoleneTiffanyG** [comment]
You are a hero.

**Comment by JoleneTiffanyG** [comment]
It opened properly in Atom, but in GH Desktop it still just has wweek-3 under the course-work directory, and in that directory just says "the file is empty"

**Comment by DVSnell** [comment]
Okay should be an easy fix.  In the GitHub Desktop App, go ahead and click on the `Current Repository` button to display a list of available repositories.  If the Repo you have open in Atom is there, go ahead and click it to make it active.  

If it isn't in that list, you can add it using `File ->Add local repository` then `Choose` to navigate to and select the folder for the Repo that opens in Atom.  If you get a warning, you can instead click the `create a repository instead` link to make one.  However this will probably add another repository to your actual GitHub account.

**Comment by JoleneTiffanyG** [comment]
Unfortunately that's what I've been trying this whole time.. I keep trying to open it again and again, either by "add local repository" or "create repository" but it's still empty each time, even though it looks right in my folder organizer and now is opening all the relevant files in Atom.  I've been trying to figure it out on forums and reading related troubleshooting help pages, but either I'm not quite smart enough to understand what they're saying, or the mistake I'm making is so basic that they (or you) wouldn't consider it.

**Comment by DVSnell** [comment]
Hmm.  Here's another option.  
1. Go to your profile page here on GitHub and navigate to your repositories.  The down arrow near your little profile picture at the top should take you right there.  
2. Click your 120-work repository and there should be a green button labeled `Clone or download` Click it and it should expand down.  
3. Choose `Open in Desktop` and accept any browser prompt that will open the Repo in GitHub Desktop.
4. Then from there you should be able to click `Current repository`, right click that Repo and hit`Open in Atom`.  
5. You can right click it again and hit `Show in Explorer` if you need to move folders to it.

I can't really think of other steps, but I've got time to keep investigating.

**Comment by JoleneTiffanyG** [comment]
Ok this might make things simpler- there is no course-work file in 120-work here on GitHub either.  Only the files from our markdown project.  So I'm guessing that means I made a more fundamental and hopefully much less complicated mistake?

**Comment by JoleneTiffanyG** [comment]
Thank you so so much for your time, I can't tell you how much I appreciate all the help!

**Comment by DVSnell** [comment]
It's not a problem.  I like troubleshooting things!

I think you're right and it's probably a file/directory location issue.
Go ahead and do step 5 in my previous post and cross-reference the file location for your GitHub `120-work` with your `course-work` Repo available in Atom.  It wouldn't surprise me if one of the folders is just in the wrong location.

**Comment by JoleneTiffanyG** [comment]
Step 5 as in "Show in Explorer" right?  I did that in both GH Desktop and Atom again, and it's showing identical directory paths.  What reason would there be for it to be so different?  I guess I was under the impression that GitHub Desktop and Atom are linked/communicating, but I know almost literally nothing about any of this and am pretty thoroughly baffled.

**Comment by DVSnell** [comment]
GitHub Desktop acts as an intermediary between changes you make in Atom and the GitHub site, but only if they're both looking at the same directory.  However GitHub allows for branches to be made so you can have derivative work done.  I don't see any different branches on your GitHub page so I don't think that's the issue.

If they are both looking at the same directory, go ahead and make a new file in Atom (any file, even a new readme.md), Save the file in Atom and see if the change shows up in GitHub Desktop.

If so, then you should be good to move `course-work` into the GitHub Desktop directory location and proceed from there.

**Comment by JoleneTiffanyG** [comment]
Ok, test file did Not show up in GitHub Desktop.  I tried a couple to be sure.

**Comment by DVSnell** [comment]
Interesting.  Can you take a screenshot of the GitHub Desktop repository location and another of the Atom repository location after choosing `Show in Explorer` in each program?  Click the Address bar of the Explorer windows (the same area you circled in the very first screenshot you posted above) before taking the screenshots so we can see the actual directory address instead of the simplified plain English version.

This is quite the puzzle.

**Comment by JoleneTiffanyG** [comment]
![screenshot1-githubdesktop](https://user-images.githubusercontent.com/42923897/45268007-d84c2200-b433-11e8-9043-2980986438bf.png)
![screenshot1-atom](https://user-images.githubusercontent.com/42923897/45268009-df733000-b433-11e8-9d07-767c8f048641.png)

**Comment by DVSnell** [comment]
Curious.  When you click on `Current branch` in GitHub Desktop, do you have any others beside `master` available?

And have you tried searching your computer for that `wweek-3` folder?

**Comment by JoleneTiffanyG** [comment]
There are no others aside from **master**.    And a search for **week-3** yielded no results.

**Comment by DVSnell** [comment]
Have you been removing errant repositories from GitHub Desktop?  You can do so by Right Clicking on them while `Current repository` is open.  There might be a conflict with the multitude of .git files visible in the second screenshot.

You can try clearing out the repositories completely from GitHub Desktop and see if that removes any conflict.

Another option, which I'm a little reticent to recommend, is if your computer is mobile and you can get to campus, we can meet at the library and really carve into the problem.  Remote Desktop access is also an option to expedite the process.

**Comment by JoleneTiffanyG** [comment]
Ok I'll try removing unnecessary repositories, I wasn't sure how to do that.  If the issue persists and you're cool with helping out that would be amazing, I'm doing everything on my laptop so I'm mobile.  I'm at work but maybe tomorrow at either the library or Mcgill?  I'll get in touch.

**Comment by DVSnell** [comment]
Yeah, if that doesn't work, feel free to reach out to me with the UM mail system or ask for me at the Paw Print in the Library tomorrow.

This problem has become quite the mystery and I can't abide that!

**Comment by JoleneTiffanyG** [comment]
Ok I can't guess your email apparently.  I just saw the TA's have their lab hours set up so I can go in and ask tomorrow, or if you're around today and feel the need to Sherlock this mystery let me know!

**Comment by DVSnell** [comment]
I'll be in the Paw Print at the Library from 2 to 4:30, but I can meet anywhere afterwards, too.  What ever works for you!
