### ISSUE TITLE
Index.html

### ISSUE THREAD

**Issue by hayliesunshine** [Montana-Media-Arts/120_CreativeCoding#125]
When I do the sketch.js code, it isn't showing up on the web browser that I had open for the index page. The code is exactly the same as the example. Does anyone know if there is a setting I need to have on or something to make it show up?

**Comment by DVSnell** [comment]
Have you saved both the `sketch.js` and `index.html` in Atom before refreshing the web browser?  That was my mistake the first go around.

**Comment by RyanMiskiv** [comment]
Make sure in your directory on Atom that you have opened up the correct versions of the file, the ones that you've been editing. I know there's so many different ones that I've made that mistake a couple times.

**Comment by hayliesunshine** [comment]
You're an actual angel. Thanks!
