### ISSUE TITLE
Learning Github

### ISSUE THREAD

**Issue by HayleyGoodin** [Montana-Media-Arts/120_CreativeCoding#128]
I have tried googling and looking back through descriptions in the course but I can not for the love of me figure out how to organize my files, or even push new ones onto my master. I have uploaded my part 1 HW3 files manually from Finder but would like to know how to do it the correct way.

**Comment by wattse13** [comment]
Hello Hayley, 

I would like to try and help, but I'm not sure I completely understand your question. To me it sounds like there are two problems. 1. organizing your files. 2. uploading your files. Is that correct?

Starting with problem 1, where are you trying to organize your files? Are you using finder, a text editor like atom, or the command line? In my very limited experience using finder has been the easiest for organizing files as changes made in finder should also automatically make changes in the text editor. For example when I add a new folder in my 120_work folder, it also adds one in my text editor Atom. 

Problem 2. When you say you manually uploaded your part 1 HW3 files from finder, what do you mean? Are you having problems moving class materials from finder into your text editor program? Are you having problems uploading changes from your text editor program into your git-hub desktop application? Are you having problems pushing changes from your git-hub desktop application to the git-hub website? Or is it something else entirely? 

Do you think you could take a screen shot of your text-editor and upload it as that might help. Mine looks like:

![text-editor-atom-screenshot](https://user-images.githubusercontent.com/42781660/45351743-1cded700-b574-11e8-9c2e-b855dace968f.png)

Let me know if any of this is helpful. Sorry if I have completely misunderstood your question.

**Comment by HayleyGoodin** [comment]
I am having issues pushing the changes. I am on the github application to send the files to my github respetory and I can make changes but they are not appearing in the regular github.
