### ISSUE TITLE
Command line question

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#130]
![ss2](https://user-images.githubusercontent.com/42828220/45386510-c05dd500-b5d0-11e8-861b-4f2aeda6cdc4.PNG)
Hey guys,

I'm not a HUGE command line user, so I am having some issues with the hw.

I am attempting to create the project in Atom, and have already moved the files to where they need to go.

this is where I am stuck:

Quote from the site directions:

3. Drag the top level directory/folder from your finder or file browser to the Atom application icon.

4. From the Command Line program of your choice, navigate to the repo directory and type atom .. (NOTE: This presumes you have installed the “command line tools” for Atom).

I am kind of confused on this part. Any insight? I have the directories open in atom. but that's as far as i got.

Thanks guys, wish I could do pics :(

Edit: attached is what my atom screen looks like

**Comment by DVSnell** [comment]
So in Windows 10, the command line is now PowerShell and it should integrate directly with Atom.  I'm not really using the command line, but on opening PowerShell and typing `atom` I can get the program to open.  It already looks like you have the project (the folder/file tree on the left side of atom) open and working.

**Comment by HagenNathaniel** [comment]
I'm scared shitless of powershell, lol.

I did *old school* command line in classes years ago, and barely remember the ins and outs.

**Comment by DVSnell** [comment]
Yeah, I'm an old DOS head myself.  But still I've been able to do everything just using the Windows GUI and Atom.

**Comment by mafordah** [comment]
@HagenNathaniel I think @DVSnell pretty much covered it, but steps 3 and 4 are just different ways of opening the project in Atom. 3 being by directly dragging the directory (folder) from the file explorer into Atom to open it, and 4 using the command line to open the project by navigating to the repo directory (project folder) and typing atom .. to open it in Atom. You can also open the project directly in Atom if you already have it open. Long story short, it looks like already have the project up in Atom so you're good to go!
