### ISSUE TITLE
Index.html-Comment

### ISSUE THREAD

**Issue by Dylan-McClean** [Montana-Media-Arts/120_CreativeCoding#131]
For some reason when I launch my internet browser I have to select a button that reads "allow blocked content". If I change the settings for running scripts or activeX controls, is this a high security risk? I do have really good internet protection with Norton. I tried editing these settings but it is still trying to block the script content when I open index.html file in internet explorer from atom. Is this normal? or should I have to change something?

**Comment by DVSnell** [comment]
Internet Explorer is rather moody, in my opinion, and tends to think it knows best.  I recommend using Mozilla Firefox, Google Chrome, or even Microsoft Edge.  They also have built in protections to stop some bad code from getting through. 

To your first question, any open protocol or active script is a risk.  I think it's more important to know where and when it's safe to use them.  One would hope our classmates don't try to inject malicious code with their projects.

**Comment by Codykrull** [comment]
Just a tip for the future. If you use Chrome be wary of extensions you have installed. Sometimes things wouldn't appear correctly when I was using chrome, but it I ran it without extensions things would appear fine. Happy coding!

**Comment by DVSnell** [comment]
Yep.  Extensions are super handy and fun, but if you had, let's say NoScript for Chrome or Firefox, this class would break to a hilarious degree.  Usually, if I don't see something the way I'm expecting to see it, I turn off all my extensions and addons and try it again.

If you're not sure how your project will look, you can use http://browsershots.org/ to get a nice preview of the page in different browsers.  At the bottom of browsershots you can even change JavaScript settings and screen size.  It might take a while to run, though, but it's kinda fun to play with.
