### ISSUE TITLE
Error 404 with no apparent reason...

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#132]
Hey Guys!!

Got my code all done, but I am having an error 404 when I try to load the page...I have tried checking the path, everything...

all files are there, as you see from on of the screen shots, but it still refuses to run..

anyone got any insights as to what's going on?

I'm at the home stretch here! 

Link here:
![ss3](https://user-images.githubusercontent.com/42828220/45452430-2b73de00-b69b-11e8-943a-2296314906d8.PNG)

Screenshots here:
![ss2](https://user-images.githubusercontent.com/42828220/45452283-ce782800-b69a-11e8-921f-8c693f54d56e.PNG)
![ss1](https://user-images.githubusercontent.com/42828220/45452284-ce782800-b69a-11e8-93b8-ba124b1e6afb.PNG)

**Comment by DVSnell** [comment]
Looks like it works for me, but only if the capitalization matches your Repo exactly, so use `/HW-3/Hw-3/` for your last 2 and it should work.

**Comment by HagenNathaniel** [comment]
always is something stupid huh? haha

**Comment by HagenNathaniel** [comment]
still trying to get it to work. even if I do it exactly, I get 404, wonder why it's working for you though...my lucky probably

**Comment by DVSnell** [comment]
Correction: very last one should be `/Hw_3/`

**Comment by HagenNathaniel** [comment]
what the heck..

![ss5](https://user-images.githubusercontent.com/42828220/45454535-8577a200-b6a1-11e8-82cb-12f583322cdb.PNG)

**Comment by HagenNathaniel** [comment]
I'm missing something stupid, I know it

**Comment by DVSnell** [comment]
Well, an old school recommendation would be to clear your browser cache...  when I get to my P.C. I'll see if I can replicate it.

**Comment by DVSnell** [comment]
So, I had not yet tried to visit your site on my personal computer.  I used the address (https://hagennathaniel.github.io/Creative-Coding-120/120_Work/HW-3/Hw_3/)

And it returned:
![hagen](https://user-images.githubusercontent.com/39629030/45458109-55cf9680-b6af-11e8-8235-c11d2ec5d072.jpg)
**Cropped for filesize**

No Idea why it's not working for you, but I suspect some type of caching issue.

**Comment by HagenNathaniel** [comment]
I'll give the cache a clean, then try your url attempt.

**Comment by HagenNathaniel** [comment]
YAY!!

It worked!!

Thanks for your help, and I am sorry I was dense as granite, lol.

**Comment by lilyj521** [comment]
mine did that for a while too! I just had my hw-3 folder inside another folder so I had to put /coursework/hw-3 instead of just /hw-3

**Comment by ElijahDGarcia** [comment]
It's a lot like the file trees we worked with in week one. The URL has to point directly to the directory where the index.html file is stored. The URL is kinda like a map for your githup repository; It treats the 'homepage' as the base floor, and every folder within as a room. In your case, you had a room within a room!
