### ISSUE TITLE
Link Submissions

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#133]
Sorry to post this in the GitHub issues forum, but how are you guys making your links say "Live Hello World" instead of having the url written out?  I figured out how to make the link active but I can't see how to give it a title to click on..

**Comment by DVSnell** [comment]
On Moodle, when you click `Add a new discussion` and the entry area pops open below, click on `Use advanced editor and additional options`.  You might get a pop-up if you've already entered things in the submission area, but you can just accept it.

Once in the advanced editor, you can click the little turning downward arrow under *Message* which is called the `Show more options` button.  Now type the words you want to be turned into a link (so, "HW-3 Live Site" for example) and highlight them.  Then click the little chain-link, the `Link` icon, and enter your website address into the popup.  Include everything from the address bar, including the http information.  Then hit `Create Link` and the text you have highlighted should turn blue, becoming an active link.  And that's it.  Continue submitting as normal.

If you want to remove the link, highlight the blue text and click the `Unlink` icon which looks like a broken chain-link.

**Comment by JoleneTiffanyG** [comment]
Shoot I must have waited too long, I don't see an Edit option under my submission any more.  But thank you so much, I will use that in the future!  Thanks for all your help!
