### ISSUE TITLE
Windows, Git., Atom

### ISSUE THREAD

**Issue by chloeortega** [Montana-Media-Arts/120_CreativeCoding#136]
Salutations virtual acquaintances ^-^ 

I have been curious about something while using Atom, in my Project window I have 2 folders showing up called _.git_ and _.gitattributes_ in the tutorial videos and some screenshots of others work, I don't think I've ever come across them, I was just wondering if anyone else has these showing up if you use Atom and if it's normal for them to be there. 
![files](https://user-images.githubusercontent.com/42819666/45470269-618c7e80-b6ea-11e8-849d-b10cb4e9f26b.png)

**Comment by DVSnell** [comment]
Yep.  The period in front of their names makes them "Hidden" files, only visible by the system.  They are necessary for GitHub Desktop to track changes and upload to your repository.

As an aside, you should only have one of each, and they should be inside your primary repository folder.  Looking at your screenshot, it looks like you're good to go.

**Comment by chloeortega** [comment]
Thank you for the clarification!
