### ISSUE TITLE
Study Group

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#137]
Hey guys, wanted to see if anyone feels they might benefit from working through some of these projects together.  I feel like it might save some time if we can help each other work through bugs in real time.  I'm sure we're all encountering a lot of the same issues as beginners, and probably spending a lot of extra time trying to figure out a problem that a classmate could easily explain.  If anyone wants to set up a weekly time to meet (either in Mcgill or the library) I was thinking Tuesday might be good so we're not pushing it with the due date but we've still had a chance to try the project on our own and see where difficulties might lie.   Anyone potentially interested feel free to comment and we can see which day is best.

**Comment by egriffin2** [comment]
I would HEAVILY encourage any of you to do this exact thing and create a study group!!!

**Comment by HagenNathaniel** [comment]
I do have a class at 11, and it goes to around 12:30..but after that. .I'm pretty free and clear

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JoleneTiffanyG** [comment]
Cool!  I've finished hw-4 stuff but I'm happy to meet up if people want to this week.  And we can do any day, or multiple days, and it can change each week.  I think I'm going to just keep this open for a while so more people can have input on days/times and chime in when we get to more difficult projects if need be.

**Comment by HagenNathaniel** [comment]
still working on my idea for HW-4, I'll be on campus tommorrow, my class starts at 11, and ends around 12:30 or so, as I stated before..

After that, I tend to head to the UC center, seems about the best place to plug my laptop in, and work on stuff, and game after I finish :P

**Comment by HagenNathaniel** [comment]
so far, I got my "body parts" created, but for whatever reason, I seem to be unable to show the preview on my system, at least on my desktop..

I'll see if the laptop has the same issue, cuz I am DAMN sure the size and location on the screen isn't right, I just did the 'preliminary' shapes and put them somewhere close to each other, lol!

Have a few other problems I am sure some hands on help would help me deal with. so, be great to meet up after my only class of the day tomorrow.

**Comment by JoleneTiffanyG** [comment]
I'm probably more behind than anyone else in this class honestly, but if you've tried office hours and TA's I'd be happy to have a look, though I don't think I would be able to troubleshoot it based on what you've posted.  I'm probably going to start going to Mcgill regularly starting with the next project (hw-5), that way there will at least be someone a little more advanced around to give guidance!  That might be a good plan if the issues forum can't assist with this particular thing

**Comment by HagenNathaniel** [comment]
honestly haven't tried them, so far I've had little trouble until this one..

Once I get the 'preview' thing down, it doesn't seem I'll struggle much.

started this late, due to studying for a government exam this thursday..

I attached what I've done so far, been adding some color to the shapes, but that's all I've done so far besides the base code..

I'll probably start doing the same as you, otherwise as we go along, I'll be in deep guano..

[HW-4.zip](https://github.com/Montana-Media-Arts/120_CreativeCoding/files/2390942/HW-4.zip)

**Comment by HagenNathaniel** [comment]
edit to previous: I've added the ; to the fill() code entries..
![ss10](https://user-images.githubusercontent.com/42828220/45661467-e7c60d80-baba-11e8-8ae4-6a351ecdaac5.PNG)

**Comment by HagenNathaniel** [comment]
added a head too, almost spaced that, lol.

**Comment by DVSnell** [comment]
I see you caught the semicolons, but you're missing a comma on line 33.  I think one thing to keep in mind is that you have a bunch of `draw` functions.  Javascript kinda views these as a variable with the name of `draw` (for lack of an easier explanation) so you keep overwriting it with each new `draw` function.

You also didn't close off the setup curly bracket till the very end of the script. so your `function draws` are nested inside the `function setup`.

If you install the package linter-jshint  in atom, you can see your warnings and errors at the bottom of the screen ala 
![hagenhw4](https://user-images.githubusercontent.com/39629030/45661826-6cfdf200-babc-11e8-9898-954a209e7d04.jpg)

Still working on getting things to show up, though.

**Comment by DVSnell** [comment]
Also, check your `create canvas` line.  ;)

**Comment by HagenNathaniel** [comment]
OH, so I should just make one single 'draw' function, and have all the ellipses there?

would make things easier, lol.

I'll look at that package too,  thanks!

**Comment by HagenNathaniel** [comment]
any way to preview this? I need to do some adjusting I'm sure on placements, lol!

**Comment by DVSnell** [comment]
There's a package for Atom called `html-preview` that's very handy.  After installing it, select the `index.html` used for this project so it opens as another tab in Atom.  While that tab is active, select the menu item `Packages -> HTML Preview -> Turn Preview On` and Atom will make another pane with a mini web browser using the index.  Now, while you edit your `sketch.js` it will update the preview every time you save.

**Comment by HagenNathaniel** [comment]
thanks, I'll give that a shot!

I'll also edit my functions, since I think I understand what you were getting at earlier

**Comment by HagenNathaniel** [comment]
in case anyone wants to meet, I am sitting at the UC center commons area now.

**Comment by HagenNathaniel** [comment]
what I am doing now, is copying all my ellipse's onto wordpad, and then moving them to the upper level of the sketch,.js file, after the 'create canvas' (fixed that issue, ty sir), and then removing the functions and the brackets that are unneeded..

So far, with preview on, I am seeing a blank screen, but I assume that's a result of the code being all weird.

hopefully, it sorts itself out enough for me to finish this project in the next day or so.
![ss11](https://user-images.githubusercontent.com/42828220/45709787-14713800-bb42-11e8-9436-72b866e84bbb.PNG)

**Comment by HagenNathaniel** [comment]
new code:

more than likely my comments are wrong now, lol...but it's consolidated, and not showing errors...but as you can see, it still won't show a preview :(

If needed I can post the zip file so you can look yourself :P 
![ss12](https://user-images.githubusercontent.com/42828220/45711736-c101e880-bb47-11e8-807a-7c8e9542e442.PNG)

**Comment by jballas** [comment]
@HagenNathaniel  double check that there is a closed curly bracket for your setup function. It needs to happen before you start the draw function. I don't see one on line 13. Instead it looks like there is an extra one at the very bottom of your code in line 54 and 55. I hope that helps gets your preview up and running.

**Comment by HagenNathaniel** [comment]
added, still no go, really getting annoying

![ss13](https://user-images.githubusercontent.com/42828220/45715341-4b027f00-bb51-11e8-8b59-4a66fab378f0.PNG)

**Comment by HagenNathaniel** [comment]
starting to think I should just modify the HW-3.... piece by piece..

**Comment by HagenNathaniel** [comment]
yeah, that's what I'll do...it's working right anyway..

Update soon :)

**Comment by cassadys** [comment]
Pretty sure createCanvas should have a capital "C"

**Comment by HagenNathaniel** [comment]
you're right, lol! Didn't notice that in my other one when I looked...

It works now :)

**Comment by HagenNathaniel** [comment]
and this is why you have a second/third/20th set of eyes!

thanks guys :)

**Comment by HagenNathaniel** [comment]
fixed the code, now trying to get it to work in git....

**Comment by HagenNathaniel** [comment]
got it!

**Comment by cassadys** [comment]
Awesome, glad you got it going!  Same thing happened to me on hw-3.
