### ISSUE TITLE
Not 120 related, but urgent!

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#138]
Hello guys!!

Anyone in Justine Evans' "intro to web design" class with me?

The course is MART- 341, section 50, it's online..

I haven't seen ANY new homework since The first readme...and that was two weeks ago!!

Getting concerned something is WAAAAY wrong, and am trying to get ahold of SOMEONE in the class, since the instructor is not responding to any correspondence..

Anyone seeing the same? or are you guys actually getting any homework to unlock passed "Beginning Development"?

thank you, and I apologize for the unorthodox method...I'm just trying to figure out what is going on there :(

**Comment by MorganLong26** [comment]
Ya I'm having the same issue and I talked to two other people in our class
and they said the same thing.

**Comment by HagenNathaniel** [comment]
very strange...and concerning...there's an assignment on the schedule that was due today...and probably one last week...

But....no info, or access to it...

**Comment by brittdalton** [comment]
I had her for web design last year and for interactive media this term and it’s juat her teaching style, more relaxed and doesn’t follow the schedule exactly as some professors do. You will be fine if you just keep an eye on the material to stay on top it when it opens. She will surely adjust the schedule as she goes.

**Comment by HagenNathaniel** [comment]
interesting, but that makes me relax a little, thank you @brittdalton
