### ISSUE TITLE
Rubber Duck Debugging???

### ISSUE THREAD

**Issue by egriffin2** [Montana-Media-Arts/120_CreativeCoding#140]
![duck](https://user-images.githubusercontent.com/21352554/45766656-54ddbe00-bbf5-11e8-9c0c-b9952d4b9cb4.jpeg)

**Comment by JoleneTiffanyG** [comment]
NICE.  Thanks for sharing!!:)

**Comment by scottyG86** [comment]
Definitely using this!!!
