### ISSUE TITLE
p5 website

### ISSUE THREAD

**Issue by chloeortega** [Montana-Media-Arts/120_CreativeCoding#142]
Salutations virtual acquaintances, ^-^

I was wondering if anyone has had trouble opening the p5.js website reference page that has been linked in the course material over the past few weeks. I use *Chrome* as my default browser and when I try to open the links the website will open but have no contents to what is specified ex) nofill
![chrome](https://user-images.githubusercontent.com/42819666/45785823-03502600-bc2b-11e8-86c1-d5e943b8ff74.png)

When I copy the link address and use a different browser like *Internet Explorer* the reference page will open but will display a **Script Error**, it doesn't matter if I click yes or no or simple exit, the reference contents will display afterwards but when I try to click on a link the same **Script Error** will pop up again. 
![p5website](https://user-images.githubusercontent.com/42819666/45785966-8ffae400-bc2b-11e8-97f1-0ce3461d338e.png)

Some links to the p5.js reference pages have displayed fine in *Internet Explorer*, has anyone run into any errors like this, should I use a different browser, or click *Download* on the p5.js website and would this help me view the contents of the links in the weekly material?

**Comment by DVSnell** [comment]
Are your browsers fully up to date?

Another thing to check is your security settings.  They may be preventing certain scripts from running.

**Comment by mafordah** [comment]
I'm in Chrome and have had this happen a couple of times, but I was able to go directly to the p5 website the search for the command directly and have it come up.

**Comment by chloeortega** [comment]
@DVSnell Yes my browsers are up to date but I'm going to look into the security settings again because besides this I've had websites be blocked and even if I try to use the *proceed unsafe* it still takes me back to the same privacy error page and I've had to open the website in *Internet Explorer* for example when I downloaded Atom. Thank you for your response!

@mafordah I wonder why it does this, I'll probably just have to search for the reference page about whatever command directly from now on like you mentioned.  Thank you for your response!

**Comment by justmolliecate** [comment]
I also use chrome and it's been working fine for me.

**Comment by DVSnell** [comment]
@chloeortega Also check your anti-virus/anti-malware software.  Many of the less useful companies make deep, system-wide changes in the name of protection, regardless of impact on functionality.  I hope it helps!

**Comment by chloeortega** [comment]
@DVSnell I will! Thank you, hope it helps too!

@justmolliecate Do you use any anti-virus software on your computer?
