### ISSUE TITLE
Text won't show correctly

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#148]
Hey guys!!

Came up with a new idea, although, with my/our "basic" knowledge of the language, it's archaic as heck, lol.

anyway, my code is mostly finished...

I just need a spot of help with the text at the bottom (see copied code below)..

I cannot for the life of me, get it to display without adversely affecting my other code...

anyone wanna have a crack at it?

Code as follows:

![ss1](https://user-images.githubusercontent.com/42828220/46050796-47439f00-c0f3-11e8-99a5-fcea2b5e134d.PNG)

**Comment by cassadys** [comment]
I would try using push() and pop() to isolate part of your code and see if
it helps.

**Comment by DVSnell** [comment]
Try changing the quotation marks to apostrophes.  Or nesting the quote in apostrophes if you need them.

**Comment by spkvfx** [comment]
I think your text might be outside of your canvas. Try 

`text("Time is Money My Friend", 640, 120)`

Isn't text is anchored to the lower left?

Also, I think that there should not be a space between the function() and (parameters). This will cause most languages to throw up, and might cause your javascript to not be interpreted properly by some browsers. This could be a source of your problem as well.
