### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/120_CreativeCoding#150]
Hey everybody,

I'm working on the week five homework and I'm just trying to make a little character follow the mouse cursor, like the example on the website, but nothings popping up when I open my index. What am I doing wrong? 

here's the code

`//creating a new character
//seting it up
function setup() {
  createCanvas( windowWidth, 500 );

}

//seting the varables
let bodyAngle = 0;
let bodyRotateRate = 0;
let bodyWidth = 90;
let bodyHeight = 90;

//creating the draw function
function draw() {
    background( 'pink' );
    //no cursor on screen
    noCursor();

    //The Updating Values
    //the body rotation rate
    bodyRotateRate = ( mouseY * 0.5 ) - 20;
    // body angle to equal itself plus rotation rate
    bodyAngle = bodyAngle + bodyRotateRate;

    //***
    // character sandbox
    //***
    push();

    // character follows mouse
    translate( mouseX, mouseY );

    //***
    //BODY
    //***
    push();

    strokeWeight(8);
    fill( 'rgb(255, 116, 28)');
    rotate( radians( bodyAngle ));
    ellipse( 0, 0, bodyWidth, bodyHeight );

    //***
    //EYE
    //***
    push();

    strokeWeight(4);
    fill(255);
    //move to center of body
    translate( bodyWidth * -0.2, bodyHeight * -0.2 );
    ellipse( 0, 0, bodyWidth * 0.33, bodyHeight * 0.33 );

    //iris
    strokeWeight(2);
    fill( 'rgb(45, 255, 123)');
    ellipse( 0, 0, 10 );
    //pupul
    fill(0);
    ellipse( 0, 0, 5 );

    pop();
    pop(); // end of body 

    pop(); //End of character

}`

**Comment by mafordah** [comment]
I copied your code and threw it in atom to test it and I can see it just fine. The only thing I changed was taking the ( `  ) off each end of your code. 

This is what I put in atom.

```
//creating a new character
//seting it up
function setup() {
createCanvas( windowWidth, 500 );

}

//seting the varables
let bodyAngle = 0;
let bodyRotateRate = 0;
let bodyWidth = 90;
let bodyHeight = 90;

//creating the draw function
function draw() {
background( 'pink' );
//no cursor on screen
noCursor();

//The Updating Values
//the body rotation rate
bodyRotateRate = ( mouseY * 0.5 ) - 20;
// body angle to equal itself plus rotation rate
bodyAngle = bodyAngle + bodyRotateRate;



//***
// character sandbox
//***
push();

// character follows mouse
translate( mouseX, mouseY );

//***
//BODY
//***
push();

strokeWeight(8);
fill( 'rgb(255, 116, 28)');
rotate( radians( bodyAngle ));
ellipse( 0, 0, bodyWidth, bodyHeight );

//***
//EYE
//***
push();

strokeWeight(4);
fill(255);
//move to center of body
translate( bodyWidth * -0.2, bodyHeight * -0.2 );
ellipse( 0, 0, bodyWidth * 0.33, bodyHeight * 0.33 );

//iris
strokeWeight(2);
fill( 'rgb(45, 255, 123)');
ellipse( 0, 0, 10 );
//pupul
fill(0);
ellipse( 0, 0, 5 );

pop();
pop(); // end of body






pop(); //End of character
}

```

Are you opening the index for the right sketch?

**Comment by lilyj521** [comment]
I had the same issue last week! I ended up just copying my code, deleting that folder, making a new one, and pasting it in there, and then it worked. I still don't know what the issue is, so I don't know if your issue is the same as mine but it might be worth a try.

**Comment by hayliesunshine** [comment]
I am having the same problem, except I can see my background and my cannot see my cursor, those I know that those statements worked. However, the character I created is not showing up.

**Comment by Dani-Briggs** [comment]
@lilyj521 I did what you did and it works now, thanks.
