### ISSUE TITLE
My link is being funky

### ISSUE THREAD

**Issue by erinflint** [Montana-Media-Arts/120_CreativeCoding#152]
The link that I have submitted in my homework does not open my sketch but instead directly downloads it? I can't figure out what I've done wrong and my brain is fried. Any help is greatly appreciated.

**Comment by chloeortega** [comment]
Interesting, after you commit your hw-5 to your repo, hmm your sketch link should appear like this:
https://erinflint.github.io/120-work/HW-5/
Maybe try and duplicate your empty example, rename it hw-5, copy and paste your code and resubmit it

**Comment by erinflint** [comment]
Well that was way easier than anticipated and I suppose that just speaks to my mental capacity at this moment. Thanks so much, Chloe. Everything is up and working!

**Comment by chloeortega** [comment]
You're welcome ^-^ !
I'm happy that I could help, we're all in this together!

**Comment by HagenNathaniel** [comment]
really love seeing so much comradiere (sp) here in this course...

Last time I had a bunch of coding classes, we had a student who was getting it more than the rest of us, but refused to help us...despite repeated conversations with the instructor..

So, I was struggling throughout my time in the coding courses, which included java, c, and c++.

This course is helping me LEARN to code, and making it much easier to get help, thanks to you guys! 

Thank you :)

**Comment by chloeortega** [comment]
@HagenNathaniel Yes! The issues forum with fellow classmates has helped me out as well
