### ISSUE TITLE
My link is not working again 

### ISSUE THREAD

**Issue by Schrielle360** [Montana-Media-Arts/120_CreativeCoding#154]
What the heck. My link worked the last two weeks but this week it wont? What? I did the link how I'm supposed to 
https://schrielle360.github.io/120-work/hw-5/ right spacing caps and all and it did not work gives me the error. idk.

**Comment by Schrielle360** [comment]
Figured it out e.e

**Comment by cassadys** [comment]
That link is giving me an error, but hw-4 works fine.
