### ISSUE TITLE
10/2 LAB HOURS CHANGE

### ISSUE THREAD

**Issue by egriffin2** [Montana-Media-Arts/120_CreativeCoding#157]
This week only, lab hours for Tuesday, October 2nd will be held by myself in McGill 126 from 11 to 12:30. Come visit if you need help

**Comment by HagenNathaniel** [comment]
damn, my class is at that time frame..

Would love to pick your (blanket statement) on an idea for HW6, since I haven't really gotten started on it..

I have a crazy idea, but putting the idea into life, that's another matter!
