### ISSUE TITLE
random() question:

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#159]
Hey guys, so...got an idea for part of my homework, and it involves using the random() statement.

I would like to have the random number generator create a set of numbers, that I will then use in the mathematical part of my idea..

I decided it was a good idea to try to do each part by itself, each requirement is it's own "art" segment.

Might make it a headache, but whatever...

Question is, how do I have the random function do what I want to do? I figure it'll be a global variable, and the program will use the numbers at the time it needs to.

How would I then:

1. Create the variables with random()

2. call them in the functions I want to.

**Comment by mafordah** [comment]
You can put the `random()` function into any function without making it a variable. Just put `random()` in place of the number you want to be randomized, and then specify what numbers you want it to be between, if you want. Unless you want the same random number to be applied throughout your function... Then, though I'm not sure, you might have to use a variable.

**Comment by spkvfx** [comment]
It really depends on what you want to do with your random value. How often does it change? Will it be assigned to multiple things? How many unique random values will you need?

You can place them(inline), but that can get messy.
