### ISSUE TITLE
let function not working or allowed?

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#160]
Trying to get my 'let' statements to work, but it's giving me an error on both of them, (see screenshot):

Not seeing why, it's what the w3 schools says about js....something about compatibility?
![ss 5](https://user-images.githubusercontent.com/42828220/46374005-dbaa8600-c64c-11e8-8439-4502246ff3a3.PNG)

**Comment by HagenNathaniel** [comment]
![ss 7](https://user-images.githubusercontent.com/42828220/46374706-94bd9000-c64e-11e8-91bc-0dafc4dcb496.PNG)

**Comment by DVSnell** [comment]
So, when the jshint linter was written, not all browsers supported the newest version of Javascript, ES6.  That's an error with the JS Hint Linter.  You need to make a `.jshintrc` file that says your coding in ES6 and to not return that error when using modern commands, like `let`.  If you follow the instructions in the error and use the settings in the actual linter package in Atom, you should be able to make three error disappear.

**Comment by DVSnell** [comment]
Now that I'm back at my station, here's how you fix the JSHint W104 warning:

As stated in my previous post, JSHint is only throwing the warning to remind you that the `let` variable is from a "newer" version of JavaScript that might not be supported by older browsers.  It's perfectly fine to code in, just not fully adopted.

To make the warning go away and stop cluttering up our error bar, we need to make a new file called `.jshintrc` in the same directory as our project files.  

You can do this in Atom by `right-clicking` (or `CMD+Clicking`) your project folder and choosing `New File`.  Name it `.jshintrc` and hit enter.  Put `{"esversion": 6}` on the first line, save it, and you should be good to go.

Some important notes:
* This file has NO extension.  It is simply `.jshintrc`
* Each project requires this file in it's root folder.
* You don't have to upload this file with your project so flag it to be ignored in GitHub Desktop.

This file is a configuration file that the linter will look at for various instructions, but for this particular problem we only need one line of code.  

Proper location and formatting:
![jshintrc](https://user-images.githubusercontent.com/39629030/46389187-c4d85380-c68d-11e8-9089-672a32ae8b2f.png)

**Comment by jballas** [comment]
@HagenNathaniel I noticed on Line 14 you need to have a lowercase r. `let rightShield = width - 35;`
and on Line 19, the m should be lowercase and S need capitalized: `let bm = mouseX, leftShield, rightShield;`. Hope that helps.

**Comment by HagenNathaniel** [comment]
little late to this...thanks guys!!

I'll do that as soon as I can!!
