### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by mprimeau1** [Montana-Media-Arts/120_CreativeCoding#161]
Hello, I'm having trouble with my link to my sketch

[live sketch](https://github.com/mprimeau1/120v2/hw6_algorithmic)
that should be it right? I'm just getting an error 404 for some reason. Any suggestions?

**Comment by chloeortega** [comment]
hmm your live sketch should be showing up with the link something like this: *https://mprimeau1.github.io/120v2/hw6_algorithmic*
I believe I'm seeing your live sketch with that link ^-^
