### ISSUE TITLE
The Color Conundrum or Why Don't Variables Work?

### ISSUE THREAD

**Issue by spkvfx** [Montana-Media-Arts/120_CreativeCoding#167]
I've noticed that there has been some confusion over color() vs. rgb(), and I was pretty confused by this myself … and it is a bit confusing. 

In the reference, you will not find rgb() as a base object. So if you try to say `myColor = rgb(r,g,b)`,  with r, g, and b being variables assigned elsewhere, it will not work.

However, if you say `background('rgb(255,10,10)')` it will work. Yet again, if you say `background('rgb(255,g,10)')` it will not.

I think the key here is the single-quote, that is saying to the background() that this is a 'string', and to parse out what type of data is coming it's way: whether its rgb, rgba, or rgb/a as percentage … [whatever](https://p5js.org/reference/#/p5/background).

So when you say `myColor = rgb(r,g,b)` it's looking for a non-existing function of method called "rgb()" and when you say `background('rgb(255,g,10)')` it's looking for a green value of 'g', which doesn't make sense.

You could make a string using the g's value, but that's no fun at all. Fortunately there is a color() object that does allow this.

So, you can say `myColor = color(r,g,b)` or `background(color(255,g,10))`, and you can even just say `background(255,g,10)` since uint8 (0-255) notation is the default.

**Comment by Codykrull** [comment]
This is very very very helpful. Thank you!
