### ISSUE TITLE
Interactive Functions?

### ISSUE THREAD

**Issue by Jackie98** [Montana-Media-Arts/120_CreativeCoding#171]
I'm posting to inquire if there is a way to design functions that interact with each other, i.e. if I wanted the actions of a circle function to affect those of a triangle function, how might I go about coding this? I may just be overthinking it, but any further input is appreciated!
Thanks!

**Comment by spkvfx** [comment]
Unless I am not quite understanding what you're meaning, I think the best way to do this would be to either return a value from the first function and write it to a variable or constant to use as a parameter in the second, or to call the second function directly from the first, though nested functions can be a bit messy.

**Comment by Jackie98** [comment]
> Unless I am not quite understanding what you're meaning, I think the best way to do this would be to either return a value from the first function and write it to a variable or constant to use as a parameter in the second, or to call the second function directly from the first, though nested functions can be a bit messy.

Yes, this seemed to work! I knew it was a simple solution, thanks :)
