### ISSUE TITLE
Ideas for OOP project

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#176]
Hey guys, Hope everyone's projects are going well, and the bugs are on vacation...lol!

I'm currently in the midst of a 3 project pileup, and am looking for ideas on this project.

My skill level isn't NEARLY the same as some of you, who continuously impress me with your amazing skills, WELL DONE I SAY!!!

I suffered pretty bad in C++ and java, so the simpler the better..

Good luck, and thank you for your time! :)

Happy coding everyone!!

**Comment by Jackie98** [comment]
Hi!
I'm definitely not the best coder in this class either, but this project was a little easier for me. I decided to make an array of bubbles, (which was just a simple collection of circles), and make them "jitter". This satisfied the requirements of the homework, and was also and overall interesting experiment with arrays and the different classes you can assign. You can see my example and code here:
[https://jackie98.github.io/120-work/hw-11/](url)
[https://github.com/Jackie98/120-work/tree/master/hw-11](url)
I found it relatively simple to do, yet it was visually appealing enough that it didn't come off as too "amateur", like some of my other projects.
I hope that helps a little bit!
Jackie

**Comment by DVSnell** [comment]
Yeah, this project was very much "Design/make a 'thing' and make it do something," so you can get a little abstract-y or realistic with it.  I hit my time limit working on mine, so there isn't a sense of forward motion yet, and I'm happy we're getting to interactions this week, but I still like the overall effect I got and ended up probably 80% of where I wanted to be.  Check out my design here: https://dvsnell.github.io/120-work/hw-11/

**Comment by Schrielle360** [comment]
Hey. 

Hope you get the pile up sorted out. You shouldnt compair yourself to others we all have strengths and weaknesses. Hope your week is going well :). good luck on your codes.

**Comment by HagenNathaniel** [comment]
sadly, I haven't...

I have a report for american Gov't, a 3 page website to build (I chose PC building, since I am a PC builder/gamer), and this project, which I haven't even started on yet...

I noticed he was a little 'late' in activating this week's assignment, so I feel like we might have some more time to do it..

Seems fair to me.

whatever I do, isn't gonna have much of a wow factor either, lol.

**Comment by HagenNathaniel** [comment]
I kind of like the 'array of objects' idea, and it seems the best idea for the timeframe I have,

Maybe I'll try making some stars and have them 'move'..perhaps across the screen in some way? or twinkle..

Any ideas on how to start that ball rolling? I am a night owl, so I like stars, lol!

**Comment by wattse13** [comment]
Making some stars sounds like a good idea!

What worked well for me this assignment was to first focus on making a class that worked the way I wanted it too before I started working with an array. After I had my functioning class I started modifying my code so that it could call an array of objects based on my class blueprints. I think the Shiffman videos follow a similar work flow. In earlier videos he writes a program with a class and then in the following videos he modifies his existing code to use an array of objects based on his previous class’s blueprints. Splitting the work into first understanding how classes work and then how classes work with arrays might help make things a little more manageable. 

Good luck!

**Comment by HagenNathaniel** [comment]
thanks, we'll see...still seems a bit daunting to my level...but it's all I can think of..

**Comment by HagenNathaniel** [comment]
ok, so I am about done with everything else I need to do prior to starting this project.

I am not finding any ready guides on using arrays to create a number of stars/objects on the screen.

I saw a few of you mentioned the videos showing how to do it..I'll look into it..but any further insights would be helpful..

time is not on my side here :(

**Comment by HagenNathaniel** [comment]
edit:

Found something useful, I'll see about adapting it...

link to found info:

https://stackoverflow.com/questions/31460262/drawing-object-arrays-with-js-canvas

looking into changing it a bit, so it either resets and reruns continuously, or change the object shape...not sure I can make things 'wiggle' or whatnot..

any ideas on either of those thoughts?

we'll see!

**Comment by HagenNathaniel** [comment]
that code isn't working...

something is missing in it...

so back to square one..

getting worried...
![ss 02](https://user-images.githubusercontent.com/42828220/48308129-44bdcd00-e51a-11e8-87ed-8f322cf60da4.PNG)

**Comment by HagenNathaniel** [comment]
ok...new idea..

Two arrays, first one stores values for x value, and the second one for the y..

The program uses them in tandem, to create the series of ellipses on the screen..
all the while, I'll have the framerate limited, so that the drawing is slow, and then it'll restart, and do it all over again..(the lowered framerate will enhance this process).

I suspect the best idea is to use a math.random function, with floor, to keep the numbers above a specific value, also, use the function to round it up to a whole number.

This will be applied to each array.

any ideas on making that happen? or have I gone off the deep end into 'YOU"VE LOST YOUR MIND" territory?
