### ISSUE TITLE
Troubleshooting a few errors..

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#178]
Hey guys, I am working on some code I have been messing with, and I am having a few errors..

Here's my code I have drawn up..

// establish array values in program

let bubbles = [];

function setup() {
createCanvas (1280, 720);

}

// use mouseDragged function to create bubbles on canvas. motion will be added later.

function mouseDragged(){
let r = random (10, 65);
let b = new Bubble(mouseX, mouseY, r);
bubbles.push(b);

}

// establish background color, and movement of bubbles on canvas.

function draw() {
  background('lightblue');

  for (let bubble of bubbles) {

    bubble.move();
    bubble.show();
  }

  for (let i = 0 < bubbles.length; i++) {
    bubbles[i].move();
    bubbles[i].show();

  }
}
// establish class and constructor.

class Bubble {
  constructor(x, y, r){
    this.x = x;
    this.y = y;
    this.r = r;

  }

  // establishing movement characgteristics.

  move() {
  this.x = this.x + random(-5, 5);
  this.y = this.y + random(-5, 5);

}
 // creating instructions to have objects show on screen.
show() {
   stroke(255);
   strokeWeight(4);
   noFill();
   ellipse(this.x, this.y, this.r * 2);
 }
}

Here's the errors I am getting, I already am aware the 'let' error isn't a problem these days..

But, judging by the fact that most errors are happening on the same lines as a previous one...

It's an error that the linter is spazzing out on...

Any assistance I can get on this? I would appreciate it. 

Thanks guys!

![err 1](https://user-images.githubusercontent.com/42828220/48318249-a2095b00-e5ba-11e8-84d1-948dd24a4c45.JPG)

**Comment by wattse13** [comment]
Hey, it looks like you are missing a semi colon after `let i;` in your for loop and just after the missing semi colon you are missing the variable `i`. When I wrote out line 29 as `for( let i = 0; i < bubbles.length; i++ )` things started working

**Comment by HagenNathaniel** [comment]
thank you so much, I'll have a look at that :)

**Comment by HagenNathaniel** [comment]
this program is one way to make a laptop breathe hard, lol!
