### ISSUE TITLE
Interaction between two classes

### ISSUE THREAD

**Issue by wattse13** [Montana-Media-Arts/120_CreativeCoding#179]
Hello everyone,
I am currently having problems getting two different objects from two different classes to interact with each other. [Here is a link to my code.](https://github.com/wattse13/120_work/blob/master/hw_12/sketch.js) At the moment the purple ellipse can be moved with the arrow keys and the yellow ellipses bounce within the screen. However, I cannot get the two to interact with each other.

I want the devour function, found in the Amoeba class, to check if it is intersecting with any objects found in the prey array. I've tried using the parameter 'other' when defining the devour function, but doing so results in an error message that 'other' is undefined. 

I have also tried defining functions in the Hunted class that would test to see if they intersect with the amoeba, but have had no success. 

I've tried following the examples in the Shiffman videos as closely as possible, but his sketches use objects created from the same class and I'm not sure if the procedure is the same as when trying to get objects from different classes to interact.  In the video 7.6 Checking Objects Intersections Part 1 he uses the following line of code when setting up a function in his Bubbles class: 

`this.intersects = function(other) { 
let d = dist( this.x, this.y, other.x, other.y );
   if( d < this.r + other.r ){
return true;
}else{
return false;
}`

I tried this as well, but the `this.intersects = function(other){}` syntax completely stopped my code from running.

Do any of you have any suggestions for how I could get both of my classes to interact? Or would it be better to create a single class and have elements from the same class interact? 

Thanks in advance! 
![screenshot 20](https://user-images.githubusercontent.com/42781660/48318284-6327d500-e5bb-11e8-8067-e0f0ea041384.png)
![screenshot 21](https://user-images.githubusercontent.com/42781660/48318285-658a2f00-e5bb-11e8-995d-b809917c8e69.png)
![screenshot 22](https://user-images.githubusercontent.com/42781660/48318286-6753f280-e5bb-11e8-82fb-e72772f23329.png)
![screenshot 23](https://user-images.githubusercontent.com/42781660/48318287-691db600-e5bb-11e8-89e5-c4b4e8177617.png)

**Comment by spkvfx** [comment]
I do not think `this.intersects` etc is a generalized function that can be just plopped into place. 

What I think you need to do is compare the current amoba's position with every hunted position (and radius). I think that this is probably what `this.intersects` is doing, but if you don't feed it `other` it won't work. 

The way I'd do that is to take the entire "hunted" array and pass it to the method responsible for this behavior (devour).

I did something comparable to this in HW 11. Check out the `getClosest()` function of the xPoint class. Here I am providing it with the parameter `pc`. This parameter corresponds to each xPoint object in the scene, as stored in the xPointcloud.points[] array (though in your case the hunted[] array will serve just be fine, you don't need a separate class for this to work).

Once I have that parameter set, I can iterate through the entire `xPointcloud.points[]` array.

**Comment by wattse13** [comment]
Hey @spkvfx, thanks for the reply! And yeah, I don't think this.intersects is a generalized function either. I took a look at your code and while I think I might kinda understand what you are doing, I'm not confident I could pull something similar off in my code before the next deadline. If I understand your suggestion correctly I should write something like:

`devour(hunted){`

     for( i = 0; i < hunted.length; i++){

          let d = dist( this.x, this.y, hunted.x, hunted.y )

               return ( d < this.r + other.r );

              }

     }

}`

I did find a work around though. I took most of the functions from the Hunted class and put them into the Amoeba class. Then I created both an array of objects and a single object based on the same Amoeba class. It is now possible to pass `other` as a parameter in the devour function without getting an error message. To make the single object and the array of objects act differently, I simply call different functions. I'm not sure if this is a good work around, but it works for the time being?

**Comment by spkvfx** [comment]
Yeah. Something like that, except you'd use `hunted[i]`, assuming that hunted is an array[] to access the individual. Also, I'd return this as an attribute of amoeba that would be initialized as something like `this.devoured = False` then `this.devoured = d < this.r + other.r ` (I think that would work?)

Then you can use `amoeba.devoured` to access the devoured condition elsewhere. Does that make sense?

I'd have to look at your code, but if it works and you're not doing unnecessary iterations, then it's fine.

**Comment by wattse13** [comment]
Hmmmm, I think I did what you described, but I get the error message that 'hunted' is not defined every time I try to pass it as a parameter in the devour() method. Trying to pass `hunted[i]` also doesn't work.

Also, I'm not entirely sure I correctly understood how to return this attribute as a function... [Here is the link to my code](https://github.com/wattse13/120_work/blob/master/empty-example/sketch.js)

**Comment by spkvfx** [comment]
You are not passing anything to `devour()` to populate the `hunted` parameter.

Change line 19 in `draw()` to `amoeba.devour(prey);`

Not sure if that will fix everything, but at least you'll have your array. As for whether it should be a class attribute or a returned value, we can discuss that once everything is working.

**Comment by wattse13** [comment]
Ahhh ok. So, I changed line 19 to `amoeba.devour(prey[i]);' I also tried `amoeba.devour(prey);`, but both gave me the same result. [Here is the code now.](https://github.com/wattse13/120_work/blob/master/empty-example/sketch.js)
So now both classes are working as they should, but still not interacting. I think I set up lines 58 through 60 in a way that will turn the background black if the amoeba object and a hunted object intersect. I think now I need to set up some sort of if statement on line 20. Something like:

`if(devour.amoeba(prey[i]) == TRUE){

     startR += 10;

}`

Thanks again for all of the help, I really appreciate it!

**Comment by spkvfx** [comment]
OH! I see now.

So you don't need to have the `for` loop within `prey()` since you're handing it one item from `prey[]` at a time. In my script I am handing it the entire array, and then doing the iteration within the method. In your case, sending it one item at a time is better, and `prey[i]` will work, but it needs to be within the iterator.

So, move line 20 (or whatever you're going to replace it with) to within the `for()` loop at line 23. Currently `i` is not defined. 

As you are likely already aware, `i` is just a variable here within the `for()` loop's scope. It isn't special, all you're doing is adding incrementing it's value until you reach the condition. you could replace it with `potato` and it would still work just fine. It's just the number of the iteration, and that corresponds with the index of the array when the condition is `i < array.length`.

Sorry if I lead you astray a bit, but the way you're envisioning this is a better solution, otherwise you'll have a redundant iterator.

**Comment by wattse13** [comment]
Hey no worries. If I'm real honest, I don't actually know what I'm doing, so you potentially misleading me isn't a big deal as I really don't know where I'm going anyways.... 

So, I replaced line 20 with an if statement that I placed in line 23. When I then tried to run the program in the browser, my internet froze up, and the program wouldn't load. After removing the for loop on line 60 in the devour method, the program loaded again, but the two classes still aren't interacting. 

I tried setting up the if statement on line 26 to say `if( amoeba.devour(prey[i]) == TRUE){...}` but doing so gives me an error message which says that `TRUE` is not defined. [Here is my code now.](https://github.com/wattse13/120_work/blob/master/empty-example/sketch.js)

**Comment by spkvfx** [comment]
the "True" boolean datatype in javascript I believe is simply `true` in all lowercase. What that error would indicate is that it's looking for a variable called `TRUE`.

I think if you just used the lowercase, it should at least complete the test.

http://www.tutorialsteacher.com/javascript/javascript-boolean
