### ISSUE TITLE
Not showing up!

### ISSUE THREAD

**Issue by EmileeK** [Montana-Media-Arts/120_CreativeCoding#180]
Hi, 
I just started my week 12 homework and so far I have created a simple class and the start of the sketch  but I have having trouble with change colors with touching.

Any suggestions on how to improve my code or how to get it to show up would be a big help!

Thanks

The code that I have right now is; 

let squares = [];

function setup() {
    createCanvas(windowWidth, 800);
   
    for( let i = 0; i < 20; i++) {
    let b = new Square(width/2, height/2, random(10, 50));
    squares.push(b);
    }
  }
function draw() {
    background('rgb(39, 235, 178)');
    
    for (let i = 0; i < squares.length; i++) {
        squares[i].move();
        squares[i].show();
        // squares[i].edge();
  
    for ( let t = 0; t < squares.lenght; t++){
      if(i != t && squares[i].intersects(squares[t]));
      squares[i].colorChange();
      squares[t].colorChange();
    }
    }
  }

class Square{

constructor(x,y,r) {
      this.x = x;
      this.k = random(x);
      this.y = random(y);
      this.j = random(y);
      this.w = r;
      this.h = r * 2;
      this.col= 0;
      
    }
colorChange(){
  this.col = color(random(255),random(255),random(255));
}
  move() {
      this.x = this.x + random(-5, 5);
      this.y = this.y + random(-5, 5);
      this.k = this.k - random(-5, 5);
    }
  show() {
      stroke(this.col);
      strokeWeight(4);
      noFill();
      rect(this.k * 2, this.y, this.h, this.w, 15);
      ellipse(this.k, this.j, this.h);
    }
}

**Comment by jballas** [comment]
@EmileeK, I noticed that length is spelled wrong in line 19, and you're missing a curly bracket  in line 20. Hopefully, that makes sense. I think I put it in the code right.
```
function draw() { 
background('rgb(39, 235, 178)');
for (let i = 0; i < squares.length; i++) {
    squares[i].move();
    squares[i].show();
    // squares[i].edge();

for ( let t = 0; t < squares.**lenght**; t++){
  if(i != t && squares[i].intersects(squares[t])) { 
  squares[i].colorChange();
  squares[t].colorChange();

} // end nested if statement
} // end nested for loop

}// end for loop
} // end draw function
```

However, I still see an error in line 20. I think you also need to create a `intersects` function in your class.

I hope that helps.
