### ISSUE TITLE
Not Showing up

### ISSUE THREAD

**Issue by MorganLong26** [Montana-Media-Arts/120_CreativeCoding#181]
I'm not sure where I went wrong, but my code won't show up live. I am trying to have it where you click on the orbs and they disappear. 
![screen](https://user-images.githubusercontent.com/42792412/48461336-70e28380-e790-11e8-9622-b5e85a113ed2.JPG) 

![screen2](https://user-images.githubusercontent.com/42792412/48461341-76d86480-e790-11e8-80f0-7a6d0f11ef31.JPG)

**Comment by JoleneTiffanyG** [comment]
I can't find the error in your code, so this isn't super helpful.  But, just to make sure you're not wasting time, the homework has to have objects that are actually aware of each other.  Just a head's up in case this is your homework project!

**Comment by jballas** [comment]
@MorganLong26 . I don't see the `this.col` from line 48, listed under the Class's `constructor()`.
