### ISSUE TITLE
Not showing and need help with mousePressed

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/120_CreativeCoding#183]
hi again,
I'm on hw-12 and my sketch is not showing up again. I also need some help with the some functions. What I want to do is to have two balls on different sides of the screen, that are two different colors, and when someone clicks and holds on the screen, the two balls will move towards the cursor and change to the same color. What I need help on is how to set up the function for the balls to move to the cursor and to change color.
Here's the code.
`//setting up the varables

let balls = [];
let num_of_balls = 2;

//setup
function setup(){
    createCanvas(windowWidth, 600);

    let init_x = 60;
    let init_y = 60;
    for (let i = 0; i < num_of_balls; i++){
      balls.push(new Ball(init_x, init_y));

      init_x += 100;
      if (init_x > width){
        init_x = 60;
        init_y += 100;
      }
    }

}

//draw
function draw(){
  background('rgb(166, 32, 66)');

  for (let i = 0; i < balls.length; i++){
    balls[i].ballCheck(balls, i);
    balls[i].wallCheck();
    balls[i].move();
    balls[i].display();
  }

}

///////
// creating the class
//////

class Ball {
  constructor(){
    this.color_one = 'blue';
    this.color_two = 'yellow';
    this.size = (20, 50);
    this.rad = this.size / 2;
    this.posX = x;
    this.posY = y / 2;
    this.deltaX = random(-5,5);
    this.deltaY = random(-5,5);
  }

  display(){
    push();

    stroke(0);
    strokeWeight(5);
    fill(this.color_one);
    translate(this.posX, this.posY);
    ellispe(0, 0, this.size);

    pop();

    push();

    stroke(0);
    strokeWeight(5);
    fill(this.color_two);
    translate((this.posX * -1), (this.posY * -1));
    ellispe(0, 0, this.size);

    pop();

  }

  move(){
    this.fri_posY += this.deltaY
    this.sec_posY += this.deltaY
  }

  wallCheck(otherBall, myVar){
      for (let n = 0; n < otherBall.length; n++){
        if (n != myVar){
          let d = dis(this.posX, this.posY, otherBall[n].posX, otherBall[n].posY);
          let combR = this.rad + otherBall[n].rad;

          if (d <= combR){
            this.deltaX *= -1;
            this.deltaY *= -1;

          }
        }
      }

  }
  mouseCheck(){

    let d = dist(this.posX, (this.posY*2), mouseX, mouseY);
    if (d > this.rad) {
      return true;
    }else {
        return false;
      }
    }
  
}`

**Comment by jballas** [comment]
@Dani-Briggs I can help debug a little. The first error I can see is the x,= and y need to be defined. So, if you stick them in your constructor on line 41.
`constructor(x,y){`

Then, in line 28 it looks like you don't have a `ball.Check` function written yet.
`//balls[i].ballCheck(balls, i);`

The next error looks like its inside the `wallCheck` function. I don't know how to explain this one. See if this works for you:
```
    wallCheck(otherBall, myVar){
        for (let n = 0; n < otherBall.length; n++){
            if (myVar !== n){
            let other = otherBall[n];
            let d = dist(this.posX, this.posY, other.posX, other.posY);
            let combR = this.rad + other.rad;

                if (d <= combR){
                    this.deltaX *= -1;
                    this.deltaY *= -1;

                }
            }
        }
    }
```
Then make sure you have the parameters in line 29:
'balls[i].wallCheck(balls, i);'

A misspelling of ellipse on line 59, and line 69, and hopefully then your circles will display.

If you fix up Line 75, and line 76, then they'll move again.
`this.posY += this.deltaY`
`this.posY += this.deltaY`

And, that's when I run out of errors I can help fix. I'm not sure how to get the balls to move toward the cursor. Anyone else have ideas?

**Comment by Dani-Briggs** [comment]
@jballas  I did what you suggested and did some other stuff, but it still won't show up. I also made an attempt at getting the mousePressed function. 
Here's what the code looks like now
 `//setting up the varables

let balls = [];
let num_of_balls = 2;


//setup
function setup(){
    createCanvas(windowWidth, 600);

    let init_x = 50;
    let init_y = 50;
    for (let i = 0; i < num_of_balls; i++){
      balls.push(new Ball(init_x, init_y));

      init_x += 100;
      if (init_x > width){
        init_x = 50;
        init_y += 100;
      }
    }


}


//draw
function draw(){
  background('rgb(166, 32, 66)');

  for (let i = 0; i < balls.length; i++){
    balls[i].ballCheck(balls, i);
    balls[i].wallCheck();
    balls[i].move();
    balls[i].display();
  }


}

function mousePressed() {
  for(let i = balls.length - 1; i >= 0; i--){
    let comeTogether = balls[i].mouseCheck();
    if (comeTogether){
      balls[i].move(mouseX, mouseY);

    }

      }
    }
  }


///////
// creating the class
//////

class Ball {
  constructor(x, y, size){
    this.color_one = 'blue';
    this.color_two = 'yellow';
    this.size = (20, 50);
    this.rad = this.size / 2;
    this.posX = x;
    this.posY = y / 2;
    this.deltaX = random(-5,5);
    this.deltaY = random(-5,5);
  }

  display(){
    push();

    stroke(0);
    strokeWeight(5);
    fill(this.color_one);
    translate(this.posX, this.posY);
    ellipse(0, 0, this.size);

    pop();

    push();

    stroke(0);
    strokeWeight(5);
    fill(this.color_two);
    translate((this.posX * -1), (this.posY * -1));
    ellipse(0, 0, this.size);

    pop();

  }

  move(){
    this.posY += this.deltaY
    this.posY += this.deltaY
  }

  wallCheck(){
    if (this.posX + this.rad >= width || this.posX - this.rad <= 0){
      this.deltaX *= -1;
    }
    if (this.posX + this.rad >= height || this.posY - this.rad <= 0){
      this.deltaY *= -1;
    }
}
  ballCheck(otherBall, myVar){
    for (let n = 0; n < otherBall.length; n++){
           if (myVar !== n){
           let other = otherBall[n];
           let d = dist(this.posX, this.posY, other.posX, other.posY);
           let combR = this.rad + other.rad;

               if (d <= combR){
                   this.deltaX *= -1;
                   this.deltaY *= -1;

                   if (this.color_one == 'rgb(17, 30, 108)';){
                     this.color_two = 'rgb(245, 245, 0)';
                   }else {
                     this.color_one = 'rgb(124, 252, 0)';
                     this.color_two = this.color_one;

                     }
                   }

               }
           }
       }

  mouseCheck(){

    let d = dist(this.posX, (this.posY*2), mouseX, mouseY);
    if (d > this.rad) {
      return true;
    }else {
        return false;
      }
    }

}`

**Comment by jballas** [comment]
@Dani-Briggs. Here's what I found.

In Line 46, there is an extra bracket.

In Line 110, there is an extra semi-colon.

Line 95 should be: `if (this.posY + this.rad >= height || this.posY + this.rad <= 0){`
(I changed it to this.posY, and made both of them +)

I think the yellow balls aren't showing up because of the translate function on line 80.
Maybe try: `translate((this.posX + width * 0.5), (this.posY  + height * 0.5)); `
Or hmm. try: `translate((this.posX + width) * .5, (this.posY + height)* .5);`
You can change those numbers however you like.

That should help get things showing and moving vertically. I'll keep looking through for the `mousePressed` and `mouseCheck` functions and let you know if I have anything else to suggest.

**Comment by jballas** [comment]
@Dani-Briggs. In the move()function, change one of the lines to `this. posX` and `this.deltaX`
Then they should bounce around horizontally, and change color! (but it only changes color when the blue touch blue, or yellow touch yellow. I don't understand how it works, but its exciting to see it working.

**Comment by Dani-Briggs** [comment]
@jballas thanks for the help I was able to get it to show up.
