### ISSUE TITLE
Final Project Quick Question

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#185]
I'm just baaarely starting out here, and my code seems to be broken.  Any chance someone can pinpoint what is missing or out of order here?  Basically all I want to see for right now is a black canvas with a little green rectangle at bottom center.
![screenshot 34](https://user-images.githubusercontent.com/42923897/48983107-f545d800-f0a7-11e8-8835-11840a2091f2.png)

**Comment by DVSnell** [comment]
Easy problem with a solution that will make you go, "D'oh!"

The semi-colon on line 9 makes for a sad program. ; (

**Comment by JoleneTiffanyG** [comment]
Oh. My. god.   Thank you Don ;'(
