### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#186]
I'm trying a few entirely different ideas in case things don't pan out, and this one I'm working on right now has some issues I can't find..   It's not completely broken, I can still see the black canvas, but that's all.  If anyone can see any inconsistencies here that I'm missing that would be incredibly helpful!

![screenshot 35](https://user-images.githubusercontent.com/42923897/48983797-ab152480-f0b0-11e8-9b31-6c3f8ea43dd0.png)
![screenshot 36](https://user-images.githubusercontent.com/42923897/48983799-afd9d880-f0b0-11e8-9538-a6d5392a83c9.png)
![screenshot 37](https://user-images.githubusercontent.com/42923897/48983801-b405f600-f0b0-11e8-9679-85a17430fc25.png)

**Comment by spkvfx** [comment]
Please post a link to your repository and I will try to take a look at it.

**Comment by JoleneTiffanyG** [comment]
https://github.com/JoleneTiffanyG/course-work/blob/master/Final%20Project/Game1/Combinetest/sketch.js
Ok so this is supposed to be the project, I started out with two separate sketches and made sure they each worked separately.  So this was where I combined them and I don't know if my whole approach was wrong or if I just missed a bracket when I put everything together.. Thanks for taking a look!

**Comment by JoleneTiffanyG** [comment]
https://github.com/JoleneTiffanyG/course-work/blob/master/Final%20Project/Game1/Game%20-%20Practice/sketch.js

https://github.com/JoleneTiffanyG/course-work/blob/master/Final%20Project/Game1/Game/sketch.js

And here are the two separate parts (both are working) that I was trying to combine in that sketch.

**Comment by spkvfx** [comment]
It looks like your immediate problems are stemming from the sphere classes. Unless it is a typo, it appears that you're trying to get two class object to share a single `display()` method.

This is possible using inheritance. Though this is a pretty complex topic, and I am not sure if it was covered in the course material, though I do not think it was. If you look up class inheritance you'll get pretty confused pretty quickly. At least I always have and it's something I've been trying to wrap my head around myself for a while.

I've prepared you the following applicable snippit that may help get you started:

```
let myPurpleSphere ;
let myGreenSphere ;

function setup() {
    createCanvas(800, 800);
    myPurpleSphere = new purpleSphere(100,100,100) ;
    myGreenSphere = new greenSphere(50,50,100) ;

}

function draw() {
    noLoop()
    myPurpleSphere.display();
    myGreenSphere.display();
}

class Sphere {
    constructor(x,y,radius,color) {
        this.x = x ;
        this.y = y ;
        this.radius = radius;
        this.color = color ;
        this.stroke = 2.0 ;
    }

    display() {
        push() ;
            fill(this.color) ;
            strokeWeight(this.stroke)
            ellipse(this.x,this.y, this.radius,this.radius) ;
        pop() ;
    }

}

class purpleSphere extends Sphere {
    constructor(x,y,size) {
        //const is just a constant, works like let/var but cannot be reassigned
        const radius = size/2
        super(x,y,radius,"purple") ;
    }
}

class greenSphere extends Sphere {
    constructor(x,y,size) {
        const radius = (size/2) ;
        super(x,y,radius,"green") ;
        this.stroke = 1.0 ;
    }
}
```
So here, you can think of greenSphere and purpleSphere as child classes of the Sphere super class. So all the properties that Sphere has, the greenSphere and purpleSphere inherent as well.

You'll notice that there is a `super` keyword. This is basically just calling on it's "parent's" constructor function, just as you would with `new Class(parameters)`.

So in this example you have several properties that define all Spheres as listed in the Sphere class's constructor function. These can be described by each of other child classes: purpleSphere and greenSphere, however all spheres have a default stroke weight of 2. Notice though that greenSphere reassigns this value to 1.0.

So I think there are a few ways you can do this. You can set up Sphere to be like an empty template with values defined by the child classes, or you can set up Sphere with a bunch of default values and then reassign them by the child classes (or a combination of both). 

I think defining a default generic Sphere class and then reassigning them might be a better solution, that way you just change the properties that define the child classes. In that case, I *think* it would be something like this:

```
class Sphere {
    constructor() {
        this.x = 0 ;
        this.y = 0 ;
        this.radius = 10;
        this.color = 'black' ;
        this.stroke = 2.0 ;
    }
```

and the child classes just reassign values of specific interest:
```
class purpleSphere extends Sphere {
    constructor(x,y,size) {
        this.radius = size/2
        this.x = x ;
        this.y = y ;
        this.color = 'purple'
        super() ;
    }
}
```
Both classes will pass properties to the `display()` method of the Sphere superclass, effectively allowing methods to be shared across both. 

You can also have independent methods in each of the "child" classes, so, for example, green spheres could have a unique move() method that causes green spheres to move in a wavey pattern while purple spheres have their own move() method to cause them to move in a linear pattern. Or all spheres could move the same by placing the move() method in the Sphere superclass. I'd imagine the same would go for properties and parameters as well.

This is all pretty new to me, too, so I am not 100% sure if this is all "proper" advice. But it does seem to work in this case. Don't hesitate to ask if you need clarification.

There is another way. But it's messy. You'd have to set up two different classes and then copy `display()` and `move()` and whatever other methods into both. But this can get cumbersome, considering how relatively complex these methods are and any changes to one would need to be replicated in the other.

I can think of another way, but it would require restructuring everything and would be kind of funky anyway. I think class inheritance is really what you're after.

So I think if you reformat this part of your script to something like above, you'll be closer to working.

**Comment by JoleneTiffanyG** [comment]
Wow. Okay.  I was definitely going about that all wrong.  Thank you so so much for taking all that time to explain!!!

**Comment by spkvfx** [comment]
Please let me know if you have any questions. I know I don't always explain myself clearly.

**Comment by JoleneTiffanyG** [comment]
You explained that incredibly well, that was exactly what I was looking for.  I haven't made it work yet but I found a Schiffman video on a related subject that will hopefully clarify.  Thank you so so much for your help!

**Comment by JoleneTiffanyG** [comment]
Do you know if this is a situation where I need to mess with the index.html?  Some of the examples I'm seeing look like that's what's being done..

**Comment by spkvfx** [comment]
I think if you're going to work with sound or embedded web pages you need to do that. I didn't look close enough at your script.

**Comment by JoleneTiffanyG** [comment]
Hey so I got everything sort of working-ish, and then when I added in the mouseCheck part that's commented out at the end, the code breaks.  Before that everything seems to be showing up fine.  Any ideas?  Here's a link to the current repo

https://github.com/JoleneTiffanyG/course-work/blob/master/Final%20Project/Game1/MediumGreen/sketch.js
