### ISSUE TITLE
Question on Final Due Date

### ISSUE THREAD

**Issue by MorganLong26** [Montana-Media-Arts/120_CreativeCoding#187]
I just wanted to check when the final project is due because the moodle submission says Dec 4th and the course website says Dec 11th.

**Comment by HagenNathaniel** [comment]
I'm gonna say the 11th...

But I'm curious myself

**Comment by chloeortega** [comment]
Hello there, I believe the final project is due December 11th, I didn't see anything on the moodle submission page about December 4th, the only other date I seen was December 3rd as the last day to turn in late homework.

**Comment by MorganLong26** [comment]
I believe it is due the 11th as well. Just to be safe I emailed our professor. I will let you know when I get an answer.

**Comment by MorganLong26** [comment]
Our final projects are due December 11th.
