### ISSUE TITLE
Problem Coding Music!

### ISSUE THREAD

**Issue by Jackie98** [Montana-Media-Arts/120_CreativeCoding#188]
Hello,
I've been trying for a few days to code this song into my sketch, but it renders the sketch invalid and I don't know why. I am using a local server too. Here is the code:

> var song;
var deltaX = 0;

function preload() {
  song = loadSound("Nuori prinssi 2.mp3");
}
function setup() {
  createCanvas(windowWidth, 500);
  song.play();
}

function draw() {
  background('lightblue');

  translate(deltaX, 0);
  deltaX++;

  // cloud
  noStroke();
  	fill( 255 );
  	ellipse(100,100,150,50);
  	ellipse(75,125,150,50);
  	ellipse(200,125,150,50);
  	ellipse(150,135,150,50);

  if (deltaX + 85 > width){
    deltaX = -145;

  }

}

Thanks in advance!

**Comment by spkvfx** [comment]
I did not see anything immediately wrong, assuming that the there is no extra character in front of the variable initializations fro `song` and `deltaX`. It's rendering strange here.

Did you load the sound library by uncommenting line seven in index.html from:
`<!-- <script src="p5_lib/p5.sound.min.js"></script> -->`
to:
`<script src="p5_lib/p5.sound.min.js"></script>`
