### ISSUE TITLE
"Loading" message

### ISSUE THREAD

**Issue by erinflint** [Montana-Media-Arts/120_CreativeCoding#192]
I've been trying to get my code to open on multiple browsers and a local server but every time I do it the page just shows a white screen with "Loading..." in the upper left hand corner. I'm working with a simple music-playing code and am unsure as to why it is refusing to load? Could my .mp3 file be too large? Below is a side-by-side of the "Loading" screen and my code.
![screen shot 2018-11-29 at 9 30 12 pm](https://user-images.githubusercontent.com/42758837/49268669-03845300-f41e-11e8-9c75-ce8f18236b73.png)

**Comment by JoleneTiffanyG** [comment]
Can you post a link?

**Comment by erinflint** [comment]
[https://github.com/erinflint/120-Work/blob/master/FINAL%20PROJECT%20CC/empty-example/index.html](url)

**Comment by erinflint** [comment]
My links come up with an error 404 message so I'm not sure that will be of any help...

**Comment by JoleneTiffanyG** [comment]
Oh I meant a link to your repo
