### ISSUE TITLE
keyPressed not working

### ISSUE THREAD

**Issue by erinflint** [Montana-Media-Arts/120_CreativeCoding#193]
For some reason my keyPressed function isn't working. It does just fine before I add my "Seed" variable. When I add said variable everything else stops moving. Basically I want to be able to shoot "seeds" upwards from a little moving guy ("Newton"). Not sure what I might be doing wrong. My code is copied below: 

var Newton;
var Apples = [];
var Seed = [];

function setup() {
  createCanvas(1000, 800);
  Newton = new Newton();
  //Seed = new Seed(width/2, height/2);
  for (var i = 0; i < 11; i++) {
    Apples[i] = new Apple(i*80+80, 20);
  }
}

function draw() {
background("pink");
Newton.show();

for (var i = 0; i < Seed.length; i++) {
  Seed[i].show();
  Seed[i].move();
}

for (var i = 0; i < Apples.length; i++) {
  //Apples[i].show();
}
}

function keyPressed() {
  if (key === 's') {
    var Seed = new Seed(width/2, height/2);
    Seed.push(Seed);
  }
  if (keyCode === RIGHT_ARROW) {
    Newton.move(1);
  }
  else if (keyCode === LEFT_ARROW) {
    Newton.move(-1);
  }
}

**Comment by spkvfx** [comment]
Hey Erin,

I've had problems with keyPressed in the past when trying to get to a letter key. `key` just never really seems to work for me either, though it does seem to work with keyTyped.

You can get a numeric key code for any key by using:

```
function keyPressed() {
    console.log(keyCode);
}
```

The keyCode for "s" is 83, so your code should work with:

```
if (keyCode === 83) {
     Seed.push(Seed);
}
```

**Comment by DVSnell** [comment]
@erinflint @spkvfx Check out this link for an even easier method of finding key codes.
http://keycode.info/
It's definitely one of those "Surely someone has streamlined this," things and sure beats re-memorizing ASCII tables and the like.

**Comment by erinflint** [comment]
Thank you both so much!

**Comment by erinflint** [comment]
Ok so I've changed my code with the new key code but it still isn't working? Not sure what to do now...

**Comment by erinflint** [comment]
And now for some reason my little guy is moving but my shooting "seed" is not appearing...I'm stumped.

**Comment by spkvfx** [comment]
Hey Erin. If you'd like, go ahead and commit to your repo and I will take a look at your code.

**Comment by erinflint** [comment]
[https://github.com/erinflint/120-Work/tree/master/FINAL%20PROJECT%20CC/empty-example](url)

Thank you!

**Comment by erinflint** [comment]
Still no luck with my moving "seed". Does anyone know if there is another way to do it? I want to have a little guy shoot a "seed" when the spacebar is pressed and have said "seed" hit targets at the top of the screen.

**Comment by spkvfx** [comment]
You almost have it!

First, you have a few naming issues that you need to take care of:

The array of seeds, the seed function and where you are storing the instances of the seed functions to be added to the seed array must all be named different. So to start, let's name your array something unique:

```
var Newton;
var Apples = [];
var Seeds = []; //seed array needs unique name
```

You also have a call to the Seed() function in your setup() function. This isn't needed since you just need to call of Seed() when the space key is pressed.

```
function setup() {
  createCanvas(1000, 800);
  Newton = new Newton();
  //mySeed = new Seed(width/2, height/2);    //this is not needed
  for (var i = 0; i < 11; i++) {
    Apples[i] = new Apple(i*80+80, 20);
  }
}
```
next, you just need to make a unique name for the seed function instance and push it into the seed array:

```
function keyPressed() {
  if (key === ' ') {
    const mySeed = new Seed(width/2, height/2);  //instance needs unique name.
    Seeds.push(mySeed);
  }
  if (keyCode === RIGHT_ARROW) {
    Newton.move(1);
  }
  else if (keyCode === LEFT_ARROW) {
    Newton.move(-1);

  }
}
```

or do it inline:

```
if (key === ' ') {
    Seeds.push(new Seed(width/2, height/2));
  }
```

Once you get everything refactored it should start to work:

```
var Newton;
var Apples = [];
var Seeds = [];

function setup() {
  createCanvas(1000, 800);
  Newton = new Newton();
  //mySeed = new Seed(width/2, height/2);
  for (var i = 0; i < 11; i++) {
    Apples[i] = new Apple(i*80+80, 20);
  }
}

function draw() {
background("pink");
Newton.show();

for (var i = 0; i < Seeds.length; i++) {
  Seeds[i].show();
  Seeds[i].move();
}


for (var i = 0; i < Apples.length; i++) {
  Apples[i].show();
}
}

function keyPressed() {
  if (key === ' ') {
    new Seed(width/2, height/2);
    Seeds.push(mySeed);
  }
  if (keyCode === RIGHT_ARROW) {
    Newton.move(1);
  }
  else if (keyCode === LEFT_ARROW) {
    Newton.move(-1);

  }
}
```
