### ISSUE TITLE
Help on Movement and Song not working

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/120_CreativeCoding#195]
Hi, for my project I want to create an animation where I have squares come into the frame and they create the images I want to make, which are 8-bit/16-bit versions of album covers from my favorite band and also have the music play while a cover is being built. I have it setup in a way that the squares are where they should stop moving. I need help figuring out how I get a square to move from the outside of the screen to inside the screen and stopping at a certain point. Also my music isn't playing and I did un-comment out the  thing in the index and it still won't play. I also want to figure out how to play multple songs, like as one ends a different one starts.

here's the code:
var song_a;
//var song_b;
//var song_c;

let x = width/2;
let y = height;

function setup(){
  createCanvas(windowWidth, windowHeight);
  song_a = loadSound("8-bit_sing_for_ab.mp3", loaded);
  song_a.setVolume(0.5);

}

function loaded(){
  song_a.play();
}

function draw(){
  background(200);

///*Album one - Absolution*
//***Shadow person one***
 push();
  //**body**
  fill(0, 0, 55);
  rect(550, 370, 50, 50);
  rect(500, 320, 50, 50);
  rect(450, 320, 50, 50);
  rect(500, 270, 50, 50);
  rect(450, 270, 50, 50);
  rect(400, 220, 50, 50);
  rect(400, 170, 50, 50);
  rect(400, 270, 50, 50);

  //**right leg**
  push();

  rect(450, 220, 50, 50);
  rect(450, 170, 50, 50);
  rect(450, 120, 50, 50);
  rect(450, 70, 50, 50);
  rect(450, 20, 50, 50);
  pop();

  //**left leg**
  push();
  rect(350, 170, 50, 50);
  rect(350, 120, 50, 50);
  rect(350, 70, 50, 50);
  rect(350, 20, 50, 50);
  pop();

  //**Right Arm**
  push();
  rect(550, 220, 50, 50);
  rect(600, 170, 50, 50);
  rect(650, 120, 50, 50);
  pop();

  //**left Arm**
  push();
  rect(400, 370, 50, 50);
  rect(350, 420, 50, 50);
  rect(300, 470, 50, 50);
  pop();

pop();

//**Shadow person two**
push();
 //**body**
 fill(0, 0, 55);
 translate(750, 10);
 scale(0.5, 0.5);
 rect(550, 370, 50, 50);
 rect(500, 320, 50, 50);
 rect(450, 320, 50, 50);
 rect(500, 270, 50, 50);
 rect(450, 270, 50, 50);
 rect(400, 220, 50, 50);
 rect(400, 170, 50, 50);
 rect(400, 270, 50, 50);
 //**right leg**
 push();

 rect(450, 220, 50, 50);
 rect(450, 170, 50, 50);
 rect(450, 120, 50, 50);
 rect(450, 70, 50, 50);
 rect(450, 20, 50, 50);
 pop();

 //**left leg**
 push();
 rect(350, 170, 50, 50);
 rect(350, 120, 50, 50);
 rect(350, 70, 50, 50);
 rect(350, 20, 50, 50);
 pop();

 //**Right Arm**
 push();
 rect(550, 220, 50, 50);
 rect(600, 170, 50, 50);
 rect(650, 120, 50, 50);
 pop();

 //**left Arm**
 push();
 rect(400, 370, 50, 50);
 rect(350, 420, 50, 50);
 rect(300, 470, 50, 50);
 pop();

pop();

//**standing person**
//*body*
push();

pop();

}

**Comment by jballas** [comment]
@Dani-Briggs if you move the `let x = width/2;` and `let y = height;` into the setup, then it won't cause an error.

As for the song not playing. I can't find any errors. Are you using a live server to view your index file? Or did you check it on github?

**Comment by jballas** [comment]
@Dani-Briggs I also wanted to share a Dan Shiffman video that might help. It's about the steering method. He takes data points from a word and animates them to fly around the screen. Maybe you can use this to animate your squares? Here's the video:
https://www.youtube.com/watch?v=4hA7G3gup-4&t=648s
