### ISSUE TITLE
Not sure how to fix my code or where I went wrong 

### ISSUE THREAD

**Issue by Schrielle360** [Montana-Media-Arts/120_CreativeCoding#196]
Hey guys. 
Working on my final project. 
So far the only things I want to do are : 
1) Make the chibi appear randomly up to 30 
2) Make the chibi not appear OVER its self 
3) Make the chibi 'aware' of other chibis, and the canvas boundaries 

So.... My thing is just literally not showing up. I have no idea how to fix this XD I'm 100% it has to do with my code I don't know if I'm missing something or if I messed something up or what. Please help. If you know how to fix it I'll be grateful.

**Comment by spkvfx** [comment]
First off, it looks liek you have `numOfBalls` instead of `numOfBubbles` at line 13.

However, you have a bigger issue with your bubble.js script. 

I'd suggest turning your Bubble() function into a class.

**Comment by Schrielle360** [comment]
thanks
