### ISSUE TITLE
MousePressed Issue

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#197]
Everything seems to be working fine until I add in the commented out part at the end, trying to do a mouseCheck so I can reference it and have the sphere disappear when you click inside it.  Any chance someone can see what I'm doing wrong?  here's a link to my current repo

https://github.com/JoleneTiffanyG/course-work/blob/master/Final%20Project/Game1/MediumGreen/sketch.js

**Comment by JoleneTiffanyG** [comment]
Here's what it looks like before I add in the mouseCheck part.  And then when it's not commented out it just breaks completely.  So I'm pretty sure I've isolated the problem to that, but I'm not sure.  Do I need to define "destroy" somewhere else?

file:///C:/Users/logod/Documents/School/Creative%20Coding/Assignments/120-work/course-work/Final%20Project/Game1/MediumGreen/index.html

**Comment by jballas** [comment]
@JoleneTiffanyG. Here's what I found.

In the `mousePressed function()` it needs to be `spheres2` with an S. just three small small typos there.

Then just make sure to fix line 161.
`let d = dist(this.posX2, this.pos2, mouseX, mouseY);'

The second parameter needs to be `this.posY2`

Then inside your Sphere 2 Class. It looks like the `mouseChecked` function is still inside the `sphereCheck`. Those need to be separated.

**Comment by JoleneTiffanyG** [comment]
Thanks so much for your response I really appreciate it!

**Comment by JoleneTiffanyG** [comment]
With those typos fixed the code will show up, but the mousePressed function still doesn't work.  Any idea why?

**Comment by jballas** [comment]
Were you able to update Line 55 and Line 59 from `sphere2`, to `spheres2' with an s?

**Comment by JoleneTiffanyG** [comment]
No I missed that!  Oh my gosh it works now!!!!!!   THANK YOU!!
