### ISSUE TITLE
Rotating issue

### ISSUE THREAD

**Issue by RyanMiskiv** [Montana-Media-Arts/120_CreativeCoding#198]
I'm trying to get an object to just rotate in its place in my final project, but it will only rotate around the origin. Anyone know how to fix this?

**Comment by JoleneTiffanyG** [comment]
Daniel Shiffman has some super amazing videos on Youtube where he address this exact issue, and he does some off-screen visualization examples that are incredibly helpful for explaining how it works!  I'll post the link if I find the specific one I have in mind, but if you Google or search in Youtube for "Schiffman p5 rotation" or something similar it should pop right up!

**Comment by JoleneTiffanyG** [comment]
here I found a link to the video I was thinking of, this should help!!

https://www.youtube.com/watch?v=o9sgjuh-CBM

**Comment by RyanMiskiv** [comment]
Thanks for the video, unfortunately I'm still having issues. The object is now rotating around the correct point, however it is being drawn very far from it and I can't figure out why

**Comment by RyanMiskiv** [comment]
[Current Repo](https://github.com/RyanMiskiv/120-work/tree/master/final)

**Comment by RyanMiskiv** [comment]
I've actually got it working now somewhat. Thanks!
