### ISSUE TITLE
Printing Text Issue

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#201]
Everything is working, except that I just added the indices on the first couple lines and the function at the veerrry end, trying to get my text to print out when a splice happens (when "destroy" is true and the sphere is spliced out of the array).  I can't get anything to print, is splice even a function that can be used like that, or is there a different way I would have to do this?  Link to current repo-

https://github.com/JoleneTiffanyG/course-work/blob/master/Final%20Project/Game1/Integrate/sketch.js

**Comment by spkvfx** [comment]
I am not 100% sure what you're trying to do, but a few observations.

Splice() does not return any value. I think you mean for indices to be returned, so you'll need `return indices` at the end.

splice() is also not called on, as far as I can tell, so `indices` value does not change: `sentence[indices]` will always return "nice"

However, the text is not being drawn because it is not being executed in the `draw()` function. Placing the whole thing within `mousepressed()` does work in the console, but I am still unable to get text:

```
function mousePressed() {
    // make the spheres check themselves
    // to see if the mouse is within them.
    for (let i = spheres.length - 1; i >= 0; i--) {
        let destroy = spheres[i].mouseCheck();
        if (destroy) {
            spheres.splice(i, 1);

            indices += 1;

            if (indices > sentence.length) {
                indices = 0;
            }

            console.log(sentence[indices]);
            
//////////does not work//////////
            fill('white');
            textSize(70);
            text(sentence[indices], 10, 250);

        }
    }
}
```

**Comment by spkvfx** [comment]
my guess is you'll need to call text() within draw(). You can try using `return indices`, but i suspect that won't work. I think you can also do:

```
if(mousePressed()) {
   //change the index and display the message
}
```

Just completely within draw(), but i could be wrong

**Comment by JoleneTiffanyG** [comment]
Cool, yeah I tried doing the if(mousePressed()) as my first choice but it didn't work, I assumed that was because I'm using mousePressed already and it can't be assigned multiple functions?  I'm still not having luck there so I might have to be creative and go another direction entirely.   Thank you so very much for your help!!

**Comment by JoleneTiffanyG** [comment]
Oh wait I just figured it out!  That was really excellent advice, thanks a million!

**Comment by spkvfx** [comment]
what did you end up doing?

**Comment by JoleneTiffanyG** [comment]
Right beneath the mousePressed function part:
indices += 1;
           if (indices > sentence.length) {
                indices = 0;
            }
            console.log(sentence[indices])

And then added the same text part separate from that immediately after calling the draw() function.  So basically exactly what you said.  Works perfectly!
