### ISSUE TITLE
"Loading..." Animation Issue

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#205]
I've created an animation in PS and am trying to bring it into my project frame-by-frame.  I'm pretty confident I'm doing it right and it's not acting like the code is broken, but when I click on the index.html the page just says "Loading..."   
   I took this part out of the rest of the code for simplicity's sake, this should definitely be right as far as I can tell.. The idea is that if I direct to the first and last frames it should fill the in-between.  If anyone has any idea why it's just Loading that would be amazing!

var sun;
function preload() {
sun = loadAnimation('Gross_A13_gifanimation0000.jpg, Gross_A13_gifanimation0020.jpg');
}
function setup() {
  createCanvas(800, 800);
}
  function draw() {
    background(255);
    animation(sun, 100, 100);
  }

**Comment by mafordah** [comment]
This might not be your problem, but I know certain browsers won't load files directly from the desktop. It might work if you open it in another browser or commit it to GitHub. If you open the code in the browser (in Google Chrome you right click and click inspect) and there's this error:

Access to image at '_where ever your image is located_' from origin 'null' has been blocked by CORS policy: The response is invalid.

The browser's your problem.

**Comment by JoleneTiffanyG** [comment]
I tried multiple browsers, and also tried using a local server :(   Any chance you might have any other ideas?  Even if they're far-fetched!  I'm at my wit's end.

**Comment by JoleneTiffanyG** [comment]
Also thanks so much for responding, you're the best
