### ISSUE TITLE
formatting question

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#206]
hey guys, I've made huge strides thanks to the instructor, and a few friends in the programming world..

But I have a minor issue..

I'll post a .zip file, since screenshotting the code won't work here..

but.. I need to figure out how to format the question text so that it isn't cut off in the upper left corner, and is RIGHT above the answer buttons..

Have a look, and see what you think!

[HW-13.zip](https://github.com/Montana-Media-Arts/120_CreativeCoding/files/2660983/HW-13.zip)

Thanks guys!

**Comment by jballas** [comment]
@HagenNathaniel 

I saw your comment in your question_display.js.  I think you're right. 
If you change  `this.posY = this.height *.5;` 
That moves the box around.
Good luck.

**Comment by HagenNathaniel** [comment]
Thanks @jballas, the other thing is I am trying to come up with a scoring system for the last screen.

I'm guessing a 'score' class will be needed.

I BELIEVE I have set up the initial screen in my sketch.js screen, so that much is started.

I also think the array is set up for the answers, so all I need to do is set up a function to look for ALL instances of 'true' and count them... then display them on a screen.

Any ideas there?
