### ISSUE TITLE
Github Pages Link not Working

### ISSUE THREAD

**Issue by ascha19** [Montana-Media-Arts/120_CreativeCoding#216]
On the last couple steps of this week's assignments but my Github.io link isn't working. I've checked the spelling and capitalization but unless I'm tired and blind (it's late so I wouldn't be surprised), I can't figure out what's wrong with it. The link I'm working with is "https:// aschave19.github.io / 120-Work / hw-3" (without the extra spaces of course) but I'm still getting an error. 

Edit: I've also looked at other issues and haven't been able to find an answer to my problem.

**Comment by christinebmartin** [comment]
GitHub.io?  try .com.  I just looked at my submission for last week, https://github.com/christinebmartin/120-work/tree/master/hw-2 and see it …/GitHub.com/… 
Are you copying from the URL in GitHub or retyping?

**Comment by christinebmartin** [comment]
also, when I compare my link to yours, mine has "tree/master/" which relate to where the page is within your GitHub.  So I'm wondering, did you publish your page, or are you still working within GitHub and not reference the website that was created

**Comment by ascha19** [comment]
I'm not talking about the link we're supposed to copy and paste into the Moodle forum that takes you to the repo in Github, I'm talking about this week's assignment where we have to publish our repo to the master branch in settings. When you publish to the master branch it eventually gives you a link that's "github.io" and doesn't have the "tree/master/" piece, and it's supposed to give you an error page when you open it. You're supposed to add "hw-3/" to the end of it to make it work, but even when I do that the link doesn't work. 

Sorry, should have made that a bit clearer.

**Comment by christinebmartin** [comment]
Gotcha!  Mine looks like: https://christinebmartin.github.io/120-work/

**Comment by christinebmartin** [comment]
does your GitHub setting show it's been published?
![image](https://user-images.githubusercontent.com/46903995/51782235-468f3980-20e2-11e9-8f19-26fd079dbffa.png)

**Comment by ascha19** [comment]
Yes, it's published. My link looks exactly like yours does, but yours works with the "hw-3/" added to it and mine doesn't work at all.

**Comment by christinebmartin** [comment]
well crud!  if you can't get it to work by Monday, I'm happy to do a screen share with you and figure it out

**Comment by ascha19** [comment]
Hey, thanks! I also ended up emailing the Prof. because I did more Googling and searching around Github, and still couldn't figure anything out. I'm wondering if it's because the computer I'm using or something at this point. Regardless, thanks for trying to help me out; I guess we'll see what happens.

**Comment by sbuff25** [comment]
you might have an empty directory copy, that was what happened to me.

**Comment by sj134629** [comment]
Maybe try retyping the code again and don't forget commit it each time you change it.

**Comment by ghost** [comment]
Going off this last comment, also make sure your file on your text editor is saved when you commit on github

**Comment by ashtonmwilson** [comment]
I find myself constantly hitting "command S" out of habit to save documents. (On a mac).

**Comment by ascha19** [comment]
None of this was the case, but I appreciate the help. Regardless, I ended up figuring it out, so it's time to close this!
