### ISSUE TITLE
Having issues with functions 

### ISSUE THREAD

**Issue by ascha19** [Montana-Media-Arts/120_CreativeCoding#220]
I'm working on both parts of this week's assignments and I can't seem to figure out how to get my functions to work. Every time I try to make a new one, such as making the sketch of Venom a function while revising [this code](https://github.com/aschave19/120-Work/blob/master/hw-4/sketch.js) from week four, everything disappears when I try to execute the code. ([Here's the attempted revision code.](https://github.com/aschave19/120-Work/blob/master/hw-4-remake/sketch.js)) Along the same lines, I just started working on my second sketch a bit and none of my [code](https://github.com/aschave19/120-Work/blob/master/hw-10/sketch.js) seems to be working. I've tried to place things differently and change things but the code's still not working.

Essentially, neither of my codes are working this week and it's really beginning to stress me out.

**Comment by tjschweitzer** [comment]
Hey so looking at your code quickly when you call the draw function the drawVenom needs to be outside the brackets.

I am on my phone so I cant test it but it should look like this. I will look at it again tomorrow if this doesn't work.


//Adding draw function
function draw() {

drawVenom()
}

//Venom function
function drawVenom() {
  stroke(45);
  fill(65);
//Background legs
  rect(200, 270, 10, 283, 0, 0, 75, 3);
  rect(350, 275, 10, 275, 0, 0, 3, 75);
//Body
  fill(75);
  noStroke()
  ellipse(300, 200, 300, 200);
//Foreground legs
  rect(250, 275, 10, 300, 0, 0, 55, 3);
  rect(400, 260, 10, 315, 0, 0, 3, 55);
//Left eye
  stroke(55);
  strokeWeight(4);
  fill(255);
  rect(155, 165, 50, 35, 15, 95, 0, 100);
//Right eye
  rect(250, 165, 75, 35, 95, 0, 95, 0);
//Tongue
  noStroke()
  fill('rgb(255, 166, 176)');
  triangle(200, 235, 215, 243, 150, 265);
  triangle(150, 265, 165, 257, 100, 240);
  triangle(100, 240, 110, 245, 105, 200);
  triangle(105, 210, 125, 210, 105, 200);
//Mouth
  noFill()
  stroke(45);
  arc(200, 225, 20, 20, 0, radians(270));
  arc(220, 232, 25, 20, radians(280), radians(215));
}

**Comment by ascha19** [comment]
@tjschweitzer Unfortunately, I've already tried that; the only result is blankness when I try to run the code. If I have the function inside the draw function, or if I remove the draw function altogether, the background color comes back but the Venom sketch is gone. Thanks for the suggestion though!

**Comment by tjschweitzer** [comment]
@aschave19 Good news! I found the errors in the code! 

From looking at your repo, there are some spots where you don't have the ending brackets before the next function in the code, and there were some missing semicolons.

This code worked for me when I ran it. let me know if you have any more questions.

```javascript

function setup() {
  createCanvas( 600, 600 );
  background( 'rgb(204, 228, 254)' );

} // ENDING BRACKET



//Adding draw function
function draw() {



drawVenom(); //~~~~~~~~This calls the function drawVenom

}// ~~~~~~~~~ADDED ENDING BRACKET FOR DRAW

//Venom function
function drawVenom() {
stroke(45);
fill(65);
//Background legs
rect(200, 270, 10, 283, 0, 0, 75, 3);
rect(350, 275, 10, 275, 0, 0, 3, 75);
//Body
fill(75);
noStroke(); //~~~~~~~~~~~MISSING SEMICOLIN
ellipse(300, 200, 300, 200);
//Foreground legs
rect(250, 275, 10, 300, 0, 0, 55, 3);
rect(400, 260, 10, 315, 0, 0, 3, 55);
//Left eye
stroke(55);
strokeWeight(4);
fill(255);
rect(155, 165, 50, 35, 15, 95, 0, 100);
//Right eye
rect(250, 165, 75, 35, 95, 0, 95, 0);
//Tongue
noStroke(); //~~~~~~~~~~~MISSING SEMICOLIN
fill('rgb(255, 166, 176)');
triangle(200, 235, 215, 243, 150, 265);
triangle(150, 265, 165, 257, 100, 240);
triangle(100, 240, 110, 245, 105, 200);
triangle(105, 210, 125, 210, 105, 200);
//Mouth
noFill(); //~~~~~~~~~~~MISSING SEMICOLIN
stroke(45);
arc(200, 225, 20, 20, 0, radians(270));
arc(220, 232, 25, 20, radians(280), radians(215));
}
```

**Comment by ascha19** [comment]
@tjschweitzer Yup, I just checked it as well and it seems to be working just fine! I'll see if I have the same problems in my other code as well. Thanks for the help!
