### ISSUE TITLE
I Clearly Have Issues With Making Objects Appear

### ISSUE THREAD

**Issue by ascha19** [Montana-Media-Arts/120_CreativeCoding#222]
Playing around with next week's content and, once again, objects aren't appearing. Maybe I should structure my code differently or maybe I should just stop coding late at night, but [here's the code](https://github.com/aschave19/120-Work/blob/master/hw-11/sketch.js) and I really appreciate any help I get.

**Comment by christinebmartin** [comment]
Looks like Your array is empty

**Comment by ascha19** [comment]
@christinebmartin That's what all three example codes' arrays look like. None of them have information in the array.
