### ISSUE TITLE
Array Isn't Working

### ISSUE THREAD

**Issue by ascha19** [Montana-Media-Arts/120_CreativeCoding#224]
My entire code was working fine until I added a necessary array. I've checked to see if I misspelled anything and I've rewritten it a couple times but the same thing happens. I know it's the array piece because if I remove/comment out the array portions (the obstacles.push line and the entire for function), the rest of the sketch works fine. The array is to call in objects from another (construction) sketch. 

Here's the piece of the code that includes my issue: 
![image](https://user-images.githubusercontent.com/46611206/56844681-7ed51e00-6871-11e9-8400-88378f190c3f.png)

**Comment by tjschweitzer** [comment]
Would you be able to post your whole code for me to look at if you're still having problems? I am more than happy to look at it for ya.

**Comment by ascha19** [comment]
@tjschweitzer Just did, [here ya go](https://github.com/aschave19/120-Work/tree/master/hw-final). The issue appears to be when I call an array in sketch.js or the relationship between sketch.js and mountain.js.

**Comment by tjschweitzer** [comment]
Thanks!
I pulled your code and looked through it. It looks like the "Obstacle" function you are making in mountain.js. I think this should be set up as a class. so I converted that for you and it looks like you might want to do the same for the file nose.js 

```java
class Obstacle {
//Positioning the obstacles
constructor(){
  this.top = random(height/2);
  this.bottom = random(height/2);
  this.x = width;
  this.wi = 45;
  this.speed = 3;
}
//Drawing the obstacles
  show() {
    noStroke();
    fill('brown');
    rect(this.x, 0, this.wi, this.top);
    rect(this.x, height-this.bottom, this.wi, this.bottom);
  }

//Speed of obstacle movement
  update() {
    this.x -= this.speed;
  }
}
 
```

Another thing you're for loop in the setup function is an infinite loop 

 ```java
for (var i = 0; i =1; i++) {
  obstacles.push(new Obstacle());
}
```
The i=1 is just assigning the variable i the value of 1 
 ```java
for (var i = 0; i < 1; i++) {
  obstacles.push(new Obstacle());
}
```

**Comment by ascha19** [comment]
@tjschweitzer This did get the sketch to work again, though the nose.js file worked fine without also being turned into a class. Unfortunately, now only one obstacle appears when there should be several, which I believe was the reason it was in a different file (from what I understand anyway).

**Comment by tjschweitzer** [comment]
I am assuming you are wanting the game to be like flappy bird. what does your code look like for how the obstacles are separated from the others in the array? I can look at your repo is you update that too :)

**Comment by ascha19** [comment]
You are correct, just a chiller version of it. And it looks like I actually figured it out. I was missing a function to make more of the obstacles as well, and I even managed to figure out how to get it to work without making obstacle.js into a class.

Thanks so much for the help!
