### ISSUE TITLE
.gitattributes?

### ISSUE THREAD

**Issue by mabonmoon** [Montana-Media-Arts/120_CreativeCoding#77]
Just wondering what this .gitattributes is in my repository for the class. Apologies if this is a silly question, but I just want to keep everything organized and I am not sure what this is! Can I/should I remove it or does it matter? Thanks!
![capture](https://user-images.githubusercontent.com/35778314/35600112-6dd464d0-05e9-11e8-8e3b-87583a1bc795.PNG)

**Comment by ReadReedRed** [comment]
@mabonmoon 
A good rule of thumb in this sort of situation (one I unfortunately learned the hard way long ago) is "if you don't know what it is, don't delete it!" It's a file contributing to your repository, so unless you're confident in what it's purpose is and how it can be safely changed without impacting anything else, I'd leave it be :)

**Comment by katholmgren** [comment]
@mabonmoon Mine shows that too so I'm assuming it's important and probably shouldn't be deleted. I originally thought it was like a starting place for the file based off the "Initial commit" label next to it, but apparently it has to do with paths. Maybe this page will help: ([https://git-scm.com/docs/gitattributes]). Good luck!

**Comment by Bridger-Sanders** [comment]
I'm gonna assume it came with the GitHub folder if you put your 120-work repository in it.
Ex: **C:\Users\Bridger\Documents\GitHub\120-work**

**Comment by kya-hover** [comment]
I was wondering about the same thing...I'd just play it safe and keep it for now. :) 
Sorry I'm not much help!

**Comment by michaelmusick** [comment]
Yeah, just keep that file around. It is individual information about your git repo. I do not **believe** you will ruin anything by deleting. But on the otherhand, it is just a good file to have in Git repos.
