### ISSUE TITLE
Accessing and editing github repo and files from different computers

### ISSUE THREAD

**Issue by MarkLannenUM** [Montana-Media-Arts/120_CreativeCoding#78]
I will do most of my work in this class on my macbook at home, but would also like to do some work on my PC at work. Does anyone know how I can access and edit (and push changes) to my github repositories and 
 the files on it from two different machines? I'm assuming it's possible, just not how to do it or if there are any potential issues doing it.

Any advice appreciated!

**Comment by michaelmusick** [comment]
> No issues at all, that is one of the things git is made for. 

Just add GitHub Desktop.app to both machines. Then from GitHub.com, select open repository in GitHub Desktop. This should allow you to sync the repo on the new machine. 

The important part is this. Whenever you start to work, make sure in GutHub Desktop, you hit the "fetch" button. Then hit it again to make sure it "pulls" the changes. When you are done working, make sure you "push" the changes up to the repo. When you get to the other machine. Do the same thing. 

Fetch, pull, commit, push. That will always be your workflow. Literally, what I do everyday between machines.  


The issue will be if you forget that. Then, you will run into merge conflicts. Not a huge deal, but will likely require sometime with me, Stephanie, or one of the Lab assistants to fix.

**Comment by MarkLannenUM** [comment]
Thank you @michaelmusick! I will set that up tomorrow and post if I have any issues.

**Comment by MarkLannenUM** [comment]
Done - it is working now. Thanks for your help!
