### ISSUE TITLE
error message in atom 

### ISSUE THREAD

**Issue by mabonmoon** [Montana-Media-Arts/120_CreativeCoding#82]
Hello! I keep getting this error message when I look at any .html files in atom. Did I download the wrong package, maybe? I followed its directions to view in developer tools (second image below) but I do not understand what I am looking for. Thanks so much guys!

![capture](https://user-images.githubusercontent.com/35778314/35953706-26ef6488-0c43-11e8-8664-a465677ad2d5.PNG)
![capture 2](https://user-images.githubusercontent.com/35778314/35953722-3cc95af2-0c43-11e8-8b27-86e78ae1672c.PNG)

**Comment by ReadReedRed** [comment]
@mabonmoon
Are you able to right-click the index.html file to bring up the option to view it in a browser instead of in Atom?

**Comment by mabonmoon** [comment]
@ReadReedRed yep, that part works just fine. The error message isn't causing any problems, it is just startling when it comes up so I was just wondering. I suppose this isn't exactly an 'issue' so I hope it's okay I ask these questions here!

**Comment by michaelmusick** [comment]
You could turn the linter-html package off? Then see if it persists. If it clears it up, you may want to then uninstall and re-install the linter package.
