### ISSUE TITLE
Signed out of Git Desktop

### ISSUE THREAD

**Issue by zkoostra** [Montana-Media-Arts/120_CreativeCoding#83]
So my Git desktop app has somehow signed me out and when I try to type what I am completely sure are the correct username and password to log in, it keeps telling me they're wrong. I've logged out of like the actual git website and logged back in WITH THE SAME CREDENTIALS just to make sure I have the info right. The weird part is it's still supposedly connected to my git account in the area where it says like "link account." And it's letting me like upload the changes but not push them to actually be published. HALP.

**Comment by ReadReedRed** [comment]
@zkoostra
Yikes! I take it you haven't reset your password since making your account, right? What's your operating system? Were you using Git desktop when it did this, or did it do this upon opening the program?

**Comment by mabonmoon** [comment]
Perhaps it is case-sensitive? Was your caps lock on or you didn't/did capitalize something in your log in credentials? :( sorry I'm not more help!

**Comment by michaelmusick** [comment]
Any luck?

Sounds like you may need to reset your password on GitHub.com <http://github.com/>, then come back to the GitHub Desktop and try again.

**Comment by zkoostra** [comment]
I think that it's an error of some kind where my desktop app (mac, for the person who asked that) can't connect correctly to my git account. I've reset the password, I've quit the app and reopened it, and it still is just saying my username or password is incorrect. I KNOW it's not incorrect, I know I'm not typing it wrong. I don't know what I should do from here.

**Comment by michaelmusick** [comment]
Bummer. Are you in Missoula? Could you either swing by my office hours today (12-1:30)? Or to lab hours in 127 https://montana-media-arts.github.io/creative-coding-1/help/#lab-hours <https://montana-media-arts.github.io/creative-coding-1/help/#lab-hours> ?

**Comment by zkoostra** [comment]
I can come to office hours. Thanks, I kind of forgot that was an option lol. I'll be there.

**Comment by iballs** [comment]
@zkoostra I had the same issue. I uninstalled the whole app and reinstalled it. Everything is working fine for me now.

**Comment by alexk2313** [comment]
Whenever i have weird issues with programs on my computer i always start by uninstalling and reinstalling. I would say 80 percent of the time this fixes any issues.
