### ISSUE TITLE
Homework submissions as live links?

### ISSUE THREAD

**Issue by MarkLannenUM** [Montana-Media-Arts/120_CreativeCoding#84]
Any instructions on how to make our homework submissions on moodle live links? When I paste my links in they are just text, but I see most folks in the class know how to paste them in as live links.

Thanks!

**Comment by kur19** [comment]
Hey Mark,

Go to advanced editing and look for a drop-down menu with a link symbol
under your post window.

**Comment by MarkLannenUM** [comment]
Thank you! I had gone to the advanced editor, but didn't see a link symbol. Didn't realize that the little arrow signal was a drop-down menu...

**Comment by kur19** [comment]
:) took me awhile to find it, too.

**Comment by Franklinsamson** [comment]
oh man.. Im still having a problem with this issue
