### ISSUE TITLE
Week 1 discussion questions

### ISSUE THREAD

**Issue by dafredichini22** [Montana-Media-Arts/120_CreativeCoding#85]
The relationship between science and art is that science is opening up doors for artists that they could never have imagined to walk though. Things like VR, video games and even music videos are all types of art that would not have developed without the help of technology and science. I don’t think there is a lot of influence the other way around, however. Science is a process of finding out information and art doesn’t really help science in anyway that I can think of. But they do pair up nicely to give us great works of art.

Historically, as technology advanced, so has art. Well art has been changing throughout the ages and doesn’t need science to help with that, but we can see that art has been so to speak ‘upgraded’ with new advanced platforms like computers and cameras. Historically, science and art have been very separate. Science back in the day was slow and very there wasn’t a lot of care for it since religion and agriculture, to name a few, were more important to the average person. And historically, it has only been pretty recent as far as recorded human history that we even have a relationship between art and science.

Creative coding is definitely an art form. It allows one to not only create beautiful works of art but the coding itself could be considered an art. They say language is an art, and well coding is a language. Everyone has a unique style to their coding which makes creative coding in a way very different in the world of language. But all in all, I would say creative coding is an art form, just like photography and painting are both art forms.

**Comment by egriffin2** [comment]
Good thoughts!  Make sure you go post this as a response to Professor Musick's first post to the issues forum (https://github.com/Montana-Media-Arts/120_CreativeCoding/issues/71).  Thanks!
