### ISSUE TITLE
Tip: Indenting blocks of code on atom in MAC OS

### ISSUE THREAD

**Issue by MarkLannenUM** [Montana-Media-Arts/120_CreativeCoding#86]
I looked this tip up and am finding it very useful for this week's assignment. If you want to indent entire blocks of code in atom on mac os, all you need to do is highlight the code and press the tab button.

If you you want to decrease the indent (move all the code to the left) highlight the block of code and press shift + tab.

**Comment by kya-hover** [comment]
Cool! Thanks for the tip, I'll have to try it!

**Comment by anon-music-and-art** [comment]
Another cool package for Atom to get is called “beautify”
https://atom.io/packages/atom-beautify <https://atom.io/packages/atom-beautify>

You can invoke it from the command line in atom, and it will automatically indent your code correctly, and make it look “pretty”. It takes a heavy-hand approach though, so it is certainly not great for every instance.

**Comment by MarkLannenUM** [comment]
Thanks @anon-music-and-art - I will give that a try.

**Comment by zkoostra** [comment]
Currently using both of these suggestions and they're super helpful. thanks!
