### ISSUE TITLE
Topic 4

### ISSUE THREAD

**Issue by kya-hover** [Montana-Media-Arts/120_CreativeCoding#87]
Can anyone else see the contents for week 4? I'm wondering if they're supposed to be accessible by now...
<img width="1280" alt="screen shot 2018-02-12 at 12 05 28 pm" src="https://user-images.githubusercontent.com/35746546/36114595-ab5f22be-0fed-11e8-900c-9bfcbb11beb7.png">

**Comment by michaelmusick** [comment]
Week 4 is live on the main content site. In reviewing and editing it, I forgot to open the hw forum on moodle. I will open that up this afternoon. In the meantime, everything is live on the main content site and you can work from there.
