### ISSUE TITLE
weekly readme.md

### ISSUE THREAD

**Issue by kya-hover** [Montana-Media-Arts/120_CreativeCoding#88]
So we do have a weekly readme? At the beginning of the lesson it says, "There will be **no** new material or review for Git, GitHub, syncing local and remote repositories, markdown, Atom, **or your weekly readme,**" but at the end it says, "When you have finished with your portrait, you should;
-**write your weekly readme**,
-upload your code to GitHub,
-add you links to the HW-4 homework submission forum via Moodle"
Sorry, I'm just a little confused!

**Comment by ReadReedRed** [comment]
We still have to write one up with every assignment, he just isn't going to walk us through how to do so anymore :)

**Comment by kya-hover** [comment]
Oh, ok. Thanks! @ReadReedRed

**Comment by a25murray** [comment]
I used the template from assignment 2 I believe, hope that helps!

**Comment by alexk2313** [comment]
What i did was copy and paste the read me format i used for the past ones and just refilled in the info! i believe this will be the best strategy to use going forward in the coming weeks.
