### ISSUE TITLE
Overworked Computer?

### ISSUE THREAD

**Issue by zkoostra** [Montana-Media-Arts/120_CreativeCoding#90]
Does anyone else's computer seem like it's working REALLY hard when you're using atom? My computer rarely turns it's fan on when I'm working on a hard surface unless I'm doing something that takes a ton of power like editing video or something. My battery settings say "atom is using a significant amount of energy" and I don't care, my computer is plugged in, I just don't want it to like.. explode haha.

**Comment by ReadReedRed** [comment]
@zkoostra 
Do you have many tabs open within Atom, by any chance? Sometimes I get a buildup of tabs from assignment to assignment myself

**Comment by mabonmoon** [comment]
@zkoostra I can tell atom works my computer intensely, but it seems to be managing it well. I'd recommend keeping any other programs closed when you've got atom open. Your computer won't explode, but you might experience lag if you've got a lot of other programs running simultaniously.

**Comment by anon-music-and-art** [comment]
Another thing to try is an alternate text editor. I have been playing around with Microsoft’s Visual Studio Code, and it seems as though it may be less processor intensive than Atom. Consider giving it a try.

**Comment by ClarissaSpain** [comment]
Also try Command+option+escape to clear up other background programs.

**Comment by alexk2313** [comment]
Minimizing the strain on your processor by only using the programs you need up at the moment is always a good option. When working for the class i only have Chrome, Atom, and GitHub open to minimize the workload for my PC.
