### ISSUE TITLE
Fix if Atom throws warning (W104) upon using "let" 

### ISSUE THREAD

**Issue by ReadReedRed** [Montana-Media-Arts/120_CreativeCoding#91]
As I was declaring variables for this week's assignment, I realized Atom was throwing warnings for every line in which I used _let_, and they stated: 

"W104 - 'let' is available in ES6 (use 'esversion:6') or Mozilla JS extensions (use moz)."

I struggled for a while to find a way to add esversion:6 into my script in a way my code would accept. Upon research, I found that inserting `/*jshint esversion: 6 */` into my code cleared out the warnings no problem! 

Just thought I'd share in case anyone else was having that issue upon working with variables!

**Comment by MarkLannenUM** [comment]
Just found this tip. Thank you - finally got rid of all those yellow dots.  :)
