### ISSUE TITLE
Homework won't open in Chrome

### ISSUE THREAD

**Issue by katholmgren** [Montana-Media-Arts/120_CreativeCoding#92]
Hi guys. My homework will open in Safari but not in Chrome. When I try from the Index page, the icon just bounces a couple times on the bottom of the screen and then disappears. It has opened in Chrome in the past. Any thoughts?

**Comment by BeauSutton** [comment]
Perhaps you need to install a certain extension to your chrome browser?

**Comment by michaelmusick** [comment]
No ideas. Especially if it has worked in the past. Perhaps try restarting your computer. Also, try Firefox.

**Comment by katholmgren** [comment]
It's working now! I closed out of everything, updated my computer, updated one of the atom extensions, and restarted my computer. Thank you both.
