### ISSUE TITLE
can't open my index.html in Safari

### ISSUE THREAD

**Issue by kya-hover** [Montana-Media-Arts/120_CreativeCoding#93]
I tried opening my hw-5 index.html file in Safari and it wasn't working. I went back to my hw-4 index.html file since it worked last week and I still got the same result. Is there any way to fix this? 

<img width="1280" alt="screen shot 2018-02-21 at 1 56 27 pm" src="https://user-images.githubusercontent.com/35746546/36505114-c1966276-170f-11e8-8e6f-881e99ab8791.png">

I tried disabling the local file restrictions but a new error came up.

<img width="1280" alt="screen shot 2018-02-21 at 1 56 44 pm" src="https://user-images.githubusercontent.com/35746546/36505128-c94e2576-170f-11e8-8d30-bb25c48937d0.png">

**Comment by michaelmusick** [comment]
I am not sure. I need to check why this is occurring, as this is new to me. Out of curiosity, is it working in Firefox or Chrome? If so, use one of those for the time being.

**Comment by kya-hover** [comment]
@michaelmusick 
I tried it in Chrome and the same thing happened. My only guess is that the update on my Mac changed some things...I got it sometime during the weekend.
<img width="925" alt="screen shot 2018-02-21 at 4 44 00 pm" src="https://user-images.githubusercontent.com/35746546/36512218-a9dcb81c-1726-11e8-95a7-1288ae687d21.png">
