### ISSUE TITLE
changing the frame rate in one section of code

### ISSUE THREAD

**Issue by kya-hover** [Montana-Media-Arts/120_CreativeCoding#94]
Hey, it's me again! I was wondering if there was a way to make a specific part of my code's frame rate slower than the rest? I tried using the frameRate() function inside of a push() pop() sandbox that contained the code I want to slow down, but it still changed the frame rate of my entire code.

**Comment by ReadReedRed** [comment]
Just to check, do you have a specific frame rate set for the code outside of the push() pop()?

**Comment by kya-hover** [comment]
@ReadReedRed No, I don't.

**Comment by ReadReedRed** [comment]
@kya-hover  Maybe give that a try; specifying in one place and not in the bulk might be what's overwriting the default. Worth a shot, anyway!

**Comment by kya-hover** [comment]
@ReadReedRed Well, I tried setting the frame rate outside of my sandbox and it still had the same effect. Thanks for trying to help though! I still feel like it should be possible to have two different frame rates running, but I must be going about it wrong...
