### ISSUE TITLE
Github Desktop error

### ISSUE THREAD

**Issue by MarkLannenUM** [Montana-Media-Arts/120_CreativeCoding#97]
I created a new file in the usual place for hw-8, but when I tried to pull on Github Desktop (after fetching) I get this error.

**_error: Unable to create '/Users/marklannen/Documents/GitHub/work-120/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue._**

I've googled the error and some suggestions say I need to delete this index.lock file, but I am unable to find it.

Any suggestions?

**Comment by ReadReedRed** [comment]
Give `del .git\index.lock` a try in cmd prompt, see if that does it for ya

**Comment by MarkLannenUM** [comment]
I get this response:  -bash: del: command not found

Maybe I am not in the correct place?

**Comment by ReadReedRed** [comment]
Maybe give it a try in your computer command prompt, rather than the one for git? I know the terminology between them varies a bit, so using it in the one that comes with your computer might do it

**Comment by anon-music-and-art** [comment]
in bash, the command is `rm` for “Remove”

**Comment by MarkLannenUM** [comment]
Thanks for all the suggestions. The fix turned out to be pretty complicated, but Quinn in the lab used his wizardry and eventually sorted it out.
