### ISSUE TITLE
Keeping generated lines within bounds

### ISSUE THREAD

**Issue by MarkLannenUM** [Montana-Media-Arts/120_CreativeCoding#99]
In my homework project I am trying to get the lines that are generated and move across the screen to 'bounce' back and stay within the window rather than just running off the screen. I've pasted in the code below and the if statements are at the very bottom. 

Any ideas why the lines still run off the screen?

/*jshint esversion: 6 */
let x1 = 0;
let y1 = 0;

function setup() {
    createCanvas( windowWidth, 600 );
    background(150, 225, 150);
    for ( let i = 0; i < 10; i++) {
    }
}

function draw() {
    for ( let i = 0; i < 10; i++) {
        //
        frameRate(10);
        drawLine();
        moveLine();

    }
}

function drawLine() {
    strokeWeight(5);
    stroke(random(255), random(255), random(255));
    line(x1, y1, x1 + random(50), y1 + random(50));
}

function moveLine() {
    x1 = x1 + random(5);
    y1 = y1 + random(15);
}

// bounce lines back across screen
if (x1 > width || x1 < 0) {
    x1 = x1 * -1;
}

if (y1 > height || y1 < 0) {
    y1 = y1 * -1;
}

**Comment by ReadReedRed** [comment]
Try adding some constraints within your draw() function for x1 and y1. It'll look something like `x1 = constrain(x1, [boundary 1], [boundary 2])`. Worked for me on a previous project to keep everything in sight!

**Comment by MarkLannenUM** [comment]
Hi @ReadReedRed. Thanks for the reply! 

I moved the if statements and the constrains in to the draw loop and am closer but not all the way there. Now the lines start over from the top in a different spot and repeat. But I was hoping to get them to 'bounce' off the border. Not sure what I am missing.

Thanks again.
